### ISSUE TITLE
Error from make request: HTTP status code 400 (Invalid format for Authorization header)

### ISSUE THREAD

**Issue by doniz** [cloudflare/cf-terraforming#103]
Hello,

I had an issues when did tried to run a command to import:

```
$ source ../env.sh # source an environment variables
$ go run cmd/cf-terraforming/main.go --email $CLOUDFLARE_EMAIL --key $CLOUDFLARE_TOKEN --account $CLOUDFLARE_ACCOUNT_ID all
```

And it throw me this:
```
ERRO[0000] error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":6003,\"message\":\"Invalid request headers\",\"error_chain\":[{\"code\":6111,\"message\":\"Invalid format for Authorization header\"}]}],\"messages\":[],\"result\":null}"
```

Here my versions:

 - Terraform v0.12.7
 - Darwin donatas 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - macOS Mojave 10.14.6
 - go version go1.12.9 darwin/amd64

Also I tried to run other command instead `all` but same happen.

**Comment by doniz** [comment]
Also did tried on vagrant machine (CentOS Linux release 7.5.1804). But same stuck on making request.

**Comment by doniz** [comment]
Sorry it works. I just used global API token instead generating separate one. It should be mentioned in the README document. :)

**Comment by SicurezzaInformatica** [comment]
> Sorry it works. I just used global API token instead generating separate one. It should be mentioned in the README document. :)

When on Cloudflare You have multiple organizations the Global API key may not be available to a specific user even if admin of one account organization.
In that case which kind of permissions should have 2x API Tokens to generate to achieve the import and mantain mission? I mean import (cf-terraforming package) and mantain (terraform Cloudflare package with r/w access to org entities).
