### ISSUE TITLE
Invalid `0rtt` code generated for cloudflare_zone_settings_override type

### ISSUE THREAD

**Issue by dantman** [cloudflare/cf-terraforming#115]
Using cf-terraforming to generate a cloudflare_zone_settings_override resource type results in output like:

```tf
resource "cloudflare_zone_settings_override" "zone_settings_override_zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz" {
	name = "mydomain.com"
	settings {
		0rtt = "off"
```

This results in an error like the following in terraforming:

```
Error: Argument or block definition required

  on mydomain.cloudflare.tf line 4, in resource "cloudflare_zone_settings_override" "zone_settings_override_zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz":
  4:           0rtt = "off"

An argument or block definition is required here.
```

**Comment by mutt13y** [comment]
An argument can not begin with a 0.
I suspect that you have zero round trip time resumption enabled, however this option is not supported in the provider AFAICS
c.f. https://www.terraform.io/docs/providers/cloudflare/r/zone_settings_override.html

So while it is obviously wrong for the generator to produce invalid code I don't believe this option could be supported yet.

**Comment by dantman** [comment]
terraform-providers/terraform-provider-cloudflare#542
