### ISSUE TITLE
`undefined: util` when installing

### ISSUE THREAD

**Issue by rainboxx** [cloudflare/cf-terraforming#142]
#140 seems to have introduced a bug with the following line:

https://github.com/cloudflare/cf-terraforming/blob/7287e0c14b669d89bddceabaf91c6766ed21d953/internal/app/cf-terraforming/cmd/record.go#L199

`util` is not defined. When installing, the following error appears:

```
go/src/github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd/record.go:199:34: undefined: util
```

<details>
<summary>Full install output</summary>

```
> go get -v -u github.com/cloudflare/cf-terraforming/...
github.com/cloudflare/cf-terraforming (download)
created GOPATH=/Users/md/go; see 'go help gopath'
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd
# github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd
../../../go/src/github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd/record.go:199:34: undefined: util
```

</details>

Not sure how to solve this since I'm not familiar with Go. I will try to dig a bit into this after creating this issue but if someone already knows what to do, I'm more than happy 😊.

**Comment by flashtel** [comment]
Same issue, it's doing my head in....

go/src/github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd/record.go:199:34: undefined: util

I've tried multiple versions of go, there is an old one in the CF repository but I can't get it to "GO"

**Comment by flashtel** [comment]
One typo and 3 hours of my life are gone....

Here is the solution

https://github.com/cloudflare/cf-terraforming/pull/141/commits/8e3537756a93b92a5f94d8c33dec89028abca82f

**Comment by patryk** [comment]
Thanks for noticing, my bad I didn't notice it.
