### ISSUE TITLE
Support Dockerfile

### ISSUE THREAD

**Issue by robcohen** [cloudflare/cf-terraforming#154]
Would be great if there was a Dockerfile to use this. @adrienbrault mentioned making one in https://github.com/cloudflare/cf-terraforming/issues/48

I just spent 30 minutes trying to run cf-terraforming with no success. I am not new to Go. Seems like this could be smoother.

**Comment by prehor** [comment]
For inspiration, here is my simple `Dockerfile`:

```Dockerfile
### BUILDER
FROM golang:1.13-buster as builder

WORKDIR /go/src/cf-terraforming

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux

RUN go get -u ./...

### IMAGE
FROM gcr.io/distroless/base-debian10
COPY --from=builder /go/bin/cf-terraforming /
ENTRYPOINT ["/cf-terraforming"]
```
