### ISSUE TITLE
Doesn't properly escape double quotes when creating cloudflare_worker_script resources

### ISSUE THREAD

**Issue by kcantrel** [cloudflare/cf-terraforming#186]
If a worker has a double quote it in then it will break the "content=" variable assignment within the cloudflare_woker_script resource. A simple fix is to escape the double quote with a backslash.

Note that cf-terraforming also doesn't escape a backslash either. So, if the worker has: `\"` in it, cf-terraforming should be outputting: `\\\"`

**Comment by patryk** [comment]
Hi @kcantrel, I believe this to be fixed now. Please check it out.
