### ISSUE TITLE
cf-terraforming is not current with the latest version of the cloudflare provider version 2.0

### ISSUE THREAD

**Issue by kcantrel** [cloudflare/cf-terraforming#187]
A prime example is that cf-terraforming outputted zone=zone_name, where the latest version of the cloudflare provider needs zone_id now.

**Comment by sjscicluna83** [comment]
Im also having this issue do we know when this will get updated as i cant get a copy oo the old provider for terraform.

**Comment by patryk** [comment]
Hello both, I've updated code to fix the brokenness after the Terraform provider version 2.0 was released, but I'm going to keep this issue open, as there is several newly created resources that are missing here.

Thanks!

**Comment by jacobbednarz** [comment]
this will be addressed with some upcoming changes in #231
