### ISSUE TITLE
Ability to use ALL option with --zone

### ISSUE THREAD

**Issue by mattpascoe** [cloudflare/cf-terraforming#194]
I'd like to be able to specify a specific --zone and the ALL resources option.

I tried `cf-terraforming -z example.com all` and it simply just dumped everything from my account_id.

**Comment by georgekaz** [comment]
This definitely doesn't dump everything from your account, unless you only have a single zone. It does dump everything from that zone and account things that are global though, such as cloudflare_access_rule and cloudflare_account_member.

I agree though that when specifying a zone you don't expect these things. I've opened a similar issue here: https://github.com/cloudflare/cf-terraforming/issues/201

**Comment by jacobbednarz** [comment]
the ability to dump all configuration is being removed in #231 and will instead require you to individually request the resources to export. closing this off as we won't be pushing forward with it.

**Comment by centifanto** [comment]
seems odd to remove this ability, would be very helpful to have
