### ISSUE TITLE
some cloudflare_zone_settings_override errors

### ISSUE THREAD

**Issue by bbigras** [cloudflare/cf-terraforming#195]
It's weird, according to https://github.com/cloudflare/cf-terraforming/issues/158#issuecomment-713763172, the ciphers one should have been fixed by d9c9ae4.

```
Error: Unsupported argument

  on cloudflare.tf line 137, in resource "cloudflare_zone_settings_override" "zone_settings_override_<id>":
 137:           ciphers = [  ]

An argument named "ciphers" is not expected here.


Error: Unsupported argument

  on cloudflare.tf line 164, in resource "cloudflare_zone_settings_override" "zone_settings_override_<id>":
 164:           orange_to_orange = "off"

An argument named "orange_to_orange" is not expected here.


Error: Unsupported argument

  on cloudflare.tf line 190, in resource "cloudflare_zone_settings_override" "zone_settings_override_<id>":
 190:           visitor_ip = "on"

An argument named "visitor_ip" is not expected here.
```

cf-terraforming b5888ca6c7998a88f7f7bd8b86ee9d20f7e2dc09

Terraform v0.13.5
+ provider registry.terraform.io/-/cloudflare v2.13.2
+ provider registry.terraform.io/cloudflare/cloudflare v2.13.2

**Comment by jacobbednarz** [comment]
closing as this is against the old version of the tool and we don't yet support `cloudflare_zone_settings_override` in the newer version.
