### ISSUE TITLE
Documentation lacks steps

### ISSUE THREAD

**Issue by eduelias** [cloudflare/cf-terraforming#196]
On the "Install" section of the README file, there's an instruction "build and install the package in your go path [...]". Those steps are not clear for those who are not completely familiar with the GO language and could have been described a bit better.

**Comment by garrettgalow** [comment]
I think the wording is just a bit unclear. The go get command does that for you. The user does NOT need to build it themselves.

We will be updating the installation instructions soon and have more than 1 option going forward so closing this for now.
