### ISSUE TITLE
When exporting access_rule, zone is ignored and account level rules are returned

### ISSUE THREAD

**Issue by georgekaz** [cloudflare/cf-terraforming#201]
When running a command such as
`cf-terraforming --zone dddddeeeefffffgggggghhhhhh access_rule`

It returns rules that exclude zone id like the following:
```
resource "cloudflare_access_rule" "access_rule_12341234123412341234" {
  notes = "SPAM login attempts"
  mode = "block"
  configuration = {
    target = "ip"
    value = "12.34.56.78"
  }
 
}
```

These are valid account level rules but I don't think they should not be returned when passing a zone id.

**Comment by garrettgalow** [comment]
please try with the new version of this tool and re-open if still an issue. Access Rule should be supported.

**Comment by JLLeitschuh** [comment]
This is still occurring with the latest version of the tool. When you specify the `--zone`, you get more records generated than should be.
