### ISSUE TITLE
Facing issue while importing bunch of Cloudflare DNS records from cf-terraforming

### ISSUE THREAD

**Issue by sandeepkumarhbz** [cloudflare/cf-terraforming#205]
I used cf-terraforming utility to import DNS records terraform config(.tf) as well state file 1 month before but now it is not working.

Logically it should not add any records because both files(.tf and tfstate) has generated at same time and synced. could you please help me to resolve this issue ?

I used to run below command for end to end process.

export CLOUDFLARE_EMAIL="sandeep_kumar@iptiq.com"
export CLOUDFLARE_TOKEN="*******************"

Go to the path: /home/sandeep/folder/cf-terraforming/cmd/cf-terraforming

Below command to generate file(.tf)
sandeep@Azure:~/folder/cf-terraforming/cmd/cf-terraforming$ go run /home/sandeep/folder/cf-terraforming/cmd/cf-terraforming/main.go --email $CLOUDFLARE_EMAIL --key $CLOUDFLARE_TOKEN -z ******************** record > importing-example.tf

sandeep@Azure:~/folder/cf-terraforming/cmd/cf-terraforming$ ls
importing-example.tf main.go

then copy this configuration file(importing-example.tf) to /home/sandeep/go/bin
Then run below command to generate the state file

sandeep@Azure:~/go/bin$ ./cf-terraforming --email $CLOUDFLARE_EMAIL --key $CLOUDFLARE_TOKEN -z ********************* --tfstate record > terraform.tfstate

sandeep@Azure:~/go/bin$ ls
cf-terraforming importing-example.tf terraform.tfstate versions.tf

Append below content in importing-example.tf file

provider "cloudflare" {
version = "~> 2.0"
email = "sandeep_kumar@iptiq.com"
api_key = "*****************"
}

then run the below command.
sandeep@Azure:~/go/bin$ terraform init
sandeep@Azure:~/go/bin$ terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

# cloudflare_record.CNAME_iptiqa_com_f6da20135dbcfe28fb5f667e8da4db4f will be created
+ resource "cloudflare_record" "CNAME_iptiqa_com_f6da20135dbcfe28fb5f667e8da4db4f" {
+ created_on = (known after apply)
+ hostname = (known after apply)
+ id = (known after apply)
+ metadata = (known after apply)
+ modified_on = (known after apply)
+ name = "iptiqa.com"
+ proxiable = (known after apply)
+ proxied = true
+ ttl = 1
+ type = "CNAME"
+ value = "lumico.com"
+ zone_id = "80ce5df6bbecd290343477fa1c21206f"
}

# cloudflare_record.CNAME_test4_iptiqa_com_49c17a3b5b07c91a08a56714b3b26c8a will be created
+ resource "cloudflare_record" "CNAME_test4_iptiqa_com_49c17a3b5b07c91a08a56714b3b26c8a" {
+ created_on = (known after apply)
+ hostname = (known after apply)
+ id = (known after apply)
+ metadata = (known after apply)
+ modified_on = (known after apply)
+ name = "test4"
+ proxiable = (known after apply)
+ proxied = true
+ ttl = 1
+ type = "CNAME"
+ value = "iptiqa-lumicoagentcenter4.azurewebsites.net"
+ zone_id = "80ce5df6bbecd290343477fa1c21206f"
}

Plan: 2 to add, 0 to change, 0 to destroy.

Warning: Version constraints inside provider configuration blocks are deprecated

on importing-example.tf line 2, in provider "cloudflare":
2: version = "~> 2.0"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

**Comment by jacobbednarz** [comment]
this will be addressed with some upcoming changes in #231
