### ISSUE TITLE
Missing dependency github.com/hashicorp/terraform/helper/hashcode

### ISSUE THREAD

**Issue by pinodex** [cloudflare/cf-terraforming#210]
Running `go get -u github.com/cloudflare/cf-terraforming/...` gives the following error message:

```
package github.com/cloudflare/cf-terraforming/cmd/cf-terraforming
        imports github.com/hashicorp/terraform/helper/hashcode: cannot find package "github.com/hashicorp/terraform/helper/hashcode" in any of:
        /usr/local/go/src/github.com/hashicorp/terraform/helper/hashcode (from $GOROOT)
        /go/src/github.com/hashicorp/terraform/helper/hashcode (from $GOPATH)
```

There is also a related issue at https://github.com/hashicorp/terraform/issues/27623. It seems that it was removed from there.

**Comment by patryk** [comment]
Thanks, @pinodex, I have updated the dependency, and updated the installation command to:
```GO111MODULE=on go get -u github.com/cloudflare/cf-terraforming/...```
Please try.
