### ISSUE TITLE
Can't install the current version on Windows

### ISSUE THREAD

**Issue by davidhubyjincode** [cloudflare/cf-terraforming#215]
Installation instructions were [recently updated](https://github.com/cloudflare/cf-terraforming/commit/de5b3ab46365125616446ea0b57a04eefca139a4) by @patryk and they appear to be related to the fixes made in [Import Terraform SDK package, fixes #210](https://github.com/cloudflare/cf-terraforming/commit/ff514fd20003f3d06dac800ca03c8f0b8c006975).

Unfortunately, this command doesn't work on Windows
`C:\Users\David>GO111MODULE=on go get -u github.com/cloudflare/cf-terraforming/...
'GO111MODULE' is not recognized as an internal or external command,
operable program or batch file.`

I also added an environment variable GO111MODULE to Windows environment variables with the value on, and tried tro run the original command:
`C:\Users\David>go get -u github.com/cloudflare/cf-terraforming/...
cannot find package "github.com/hashicorp/terraform-plugin-sdk/helper/hashcode" in any of:
        C:\Program Files\Go\src\github.com\hashicorp\terraform-plugin-sdk\helper\hashcode (from $GOROOT)
        C:\Users\David\go\src\github.com\hashicorp\terraform-plugin-sdk\helper\hashcode (from $GOPATH)`
        
It looks like an out of date version of terraform-plugin-sdk might be referenced.

**Comment by jason-m-rogers** [comment]
Same issue on ubuntu:

`vagrant@ubuntu-bionic:~$ go get -v -u github.com/cloudflare/cf-terraforming/...
github.com/cloudflare/cf-terraforming (download)
github.com/cloudflare/cloudflare-go (download)
github.com/pkg/errors (download)
get "golang.org/x/net/idna": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at //golang.org/x/net/idna?go-get=1
get "golang.org/x/net/idna": verifying non-authoritative meta tag
golang.org/x/net (download)
get "golang.org/x/text/secure/bidirule": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/secure/bidirule?go-get=1
get "golang.org/x/text/secure/bidirule": verifying non-authoritative meta tag
golang.org/x/text (download)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
get "golang.org/x/text/unicode/bidi": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/bidi?go-get=1
get "golang.org/x/text/unicode/bidi": verifying non-authoritative meta tag
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
get "golang.org/x/time/rate": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at //golang.org/x/time/rate?go-get=1
get "golang.org/x/time/rate": verifying non-authoritative meta tag
golang.org/x/time (download)
github.com/hashicorp/terraform-plugin-sdk (download)
package github.com/hashicorp/terraform-plugin-sdk/helper/hashcode: cannot find package "github.com/hashicorp/terraform-plugin-sdk/helper/hashcode" in any of:
        /usr/local/go/src/github.com/hashicorp/terraform-plugin-sdk/helper/hashcode (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/terraform-plugin-sdk/helper/hashcode (from $GOPATH)
github.com/mitchellh/go-homedir (download)
github.com/sirupsen/logrus (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
get "golang.org/x/sys/internal/unsafeheader": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/internal/unsafeheader?go-get=1
get "golang.org/x/sys/internal/unsafeheader": verifying non-authoritative meta tag
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
github.com/spf13/viper (download)
github.com/fsnotify/fsnotify (download)
github.com/hashicorp/hcl (download)
github.com/agext/levenshtein (download)
github.com/apparentlymart/go-textseg (download)
github.com/mitchellh/go-wordwrap (download)
github.com/zclconf/go-cty (download)
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
github.com/magiconair/properties (download)
github.com/mitchellh/mapstructure (download)
github.com/pelletier/go-toml (download)
github.com/spf13/afero (download)
github.com/spf13/cast (download)
github.com/spf13/jwalterweatherman (download)
github.com/subosito/gotenv (download)
get "gopkg.in/ini.v1": found meta tag get.metaImport{Prefix:"gopkg.in/ini.v1", VCS:"git", RepoRoot:"https://gopkg.in/ini.v1"} at //gopkg.in/ini.v1?go-get=1
gopkg.in/ini.v1 (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)`

**Comment by jason-m-rogers** [comment]
Same issue on ubuntu:

vagrant@ubuntu-bionic:~$ go get -u github.com/cloudflare/cf-terraforming/...
package github.com/hashicorp/terraform-plugin-sdk/helper/hashcode: cannot find package "github.com/hashicorp/terraform-plugin-sdk/helper/hashcode" in any of:
        /usr/local/go/src/github.com/hashicorp/terraform-plugin-sdk/helper/hashcode (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/terraform-plugin-sdk/helper/hashcode (from $GOPATH)
package github.com/hashicorp/hcl/hcl/printer: cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
        /usr/local/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
        /home/vagrant/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)

Those packages are now in:
github.com/hashicorp/terraform-plugin-sdk/internal/helper/hashcode
github.com/hashicorp/hcl/tree/hcl1/hcl (the main branch no longer has hashicorp/hcl/hcl/printer)

Recommend reverting this update.

**Comment by davidhubyjincode** [comment]
@jason-m-rogers did you try this syntax on Ubuntu?
`GO111MODULE=on go get -u github.com/cloudflare/cf-terraforming/...`
I was able to use Ubuntu as a workaround using this command.

(While I was trying to get things working I might have run some other commands on Ubuntu which made it work)

**Comment by jason-m-rogers** [comment]
> GO111MODULE=on go get -u github.com/cloudflare/cf-terraforming/...

That worked.  Thanks!
