### ISSUE TITLE
Unclear how to use config file

### ISSUE THREAD

**Issue by burner1024** [cloudflare/cf-terraforming#218]
1. Added `CLOUDFLARE_EMAIL` and stuff to `~/.cf-terraforming.yaml`. Does nothing.
2. Configs should go to `~/.config/` dir, not to home root.

**Comment by garrettgalow** [comment]
unsure what you are trying to do with `~/.cf-terraforming.yaml` - I don't believe that is used by this tool. You should export vars like email and key/token or use something like https://github.com/jacobbednarz/cf-vault

**Comment by burner1024** [comment]
Like I said, tried `CLOUDFLARE_EMAIL` and other vars.
It's right there in the readme:
```
Usage:
  cf-terraforming [command]
...
  -c, --config string          Path to configuration file (default is $HOME/.cf-terraforming.yaml)
```

**Comment by jacobbednarz** [comment]
> Added CLOUDFLARE_EMAIL and stuff to ~/.cf-terraforming.yaml. Does nothing.

when using the configuration file option, you don't use the environment variable, you use the flag name; in your case it is `email` (drop the prefixing `--`). the environment variable and configuration file are two different options and hold a different precedence between them.

> Configs should go to ~/.config/ dir, not to home root.

i'm afraid this isn't universal as not all systems implement the XDG base directory standard so no, we don't use it by default however we may change the default in the future if it gets more adoption. if you'd like to put your configuration file there, you can and reference it using `--config` flag for it to work.

**Comment by burner1024** [comment]
> when using the configuration file option, you don't use the environment variable, you use the flag name; in your case it is email (drop the prefixing --). the environment variable and configuration file are two different options and hold a different precedence between them.

Well, I figure this information should be in the docs? That's what the issue is about.
Along with precedence info and whether these options are exclusive or mix and match.
