### ISSUE TITLE
FATA[0004] -lock, -lock-timeout, -verify-plugins, and -get-plugins options are no longer available as of Terraform 0.15: unexpected version 0.15.0 (min: -, max: 0.15.0) 

### ISSUE THREAD

**Issue by pxeger** [cloudflare/cf-terraforming#237]
### Confirmation

My issue isn't already found on the issue tracker.
I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming dev (compiled from source @ v0.1.0 a8eea8e13b153dee0a65116e98fcef331e8c5e78)

### Expected outcome

`cf-terraforming generate` works as usual

### Actual outcome

An error:

```
FATA[0004] -lock, -lock-timeout, -verify-plugins, and -get-plugins options are no longer available as of Terraform 0.15: unexpected version 0.15.0 (min: -, max: 0.15.0) 
```

This worked until Terraform v0.15.0 was released about 3 hours ago (`Wed Apr 14 15:33:02 2021 +0000`), but now it doesn't work, even though I'm still using Terraform v0.14.10. (although I tried it with Terraform v0.15.0 and it also doesn't work). It must have something to do with auto-updating?

`cf-terraforming import` still works fine.

### Steps to reproduce

1. Run `cf-terraforming -k ... -e ... -a ... -z ... --resource-type cloudflare_record generate`
2. Observe the error

**Comment by jacobbednarz** [comment]
#238 has a fix for this one and will land shortly
