### ISSUE TITLE
Unclear how to install and use

### ISSUE THREAD

**Issue by shinpei3** [cloudflare/cf-terraforming#241]
Cloned the release for linux/amd64 to Ubuntu/wsl2 on windows and built.
then I ran command below and got this result,
` $ ./cf-terraforming generate
FATA[0003] failed to detect provider installation`

This depends on terraform and its cloudflare provider plugin?
I don't  a way to fix it. I wish a description of how to install and use.

**Comment by garrettgalow** [comment]
The tool needs to be run in a directory where you have a TF file setup with the cloudflare provider installed. For a tutorial on getting started see this blog post: https://blog.cloudflare.com/cloudflares-partnership-with-hashicorp-and-bootstrapping-terraform-with-cf-terraforming/

**Comment by jacobbednarz** [comment]
there is a flag to point at a directory that isn't the current working directory (see [cmd/root.go#L80-L81](https://github.com/cloudflare/cf-terraforming/blob/83001298479ef7f2704c081eb7515797271ab6a4/internal/app/cf-terraforming/cmd/root.go#L80-L81) and `cf-terraforming help`) however it is a more advanced option and unless you know what you're doing along with understanding the Terraform internals, i would recommend only running this tool in the same directory as your Terraform installation.
