### ISSUE TITLE
Update version to latest release

### ISSUE THREAD

**Issue by garrettgalow** [cloudflare/cf-terraforming#243]
currently version is hardcoded to `dev`

https://github.com/cloudflare/cf-terraforming/blob/83001298479ef7f2704c081eb7515797271ab6a4/internal/app/cf-terraforming/cmd/version.go#L9

**Comment by jacobbednarz** [comment]
"dev" is the default version string applied to builds however released versions are controlled by the GitHub Action (https://github.com/cloudflare/cf-terraforming/blob/master/.github/workflows/release.yaml#L20-L21) reading in the created tag and when you `make build` the ldflags update it to include the git sha (https://github.com/cloudflare/cf-terraforming/blob/master/Makefile#L15)

**Comment by garrettgalow** [comment]
hm in that case, we want to move away from go get as the prescribed installation method since it does not get an updated version.

I pulled fresh with go get today and get this:

```
$ cf-terraforming version
cf-terraforming dev
```

**Comment by jacobbednarz** [comment]
ah yes, that will definitely make providing version information far harder. we do provide built binaries so what about if we redirect people to the release page (https://github.com/cloudflare/cf-terraforming/releases) instead? `go get` is more of a developer only feature anyway.

**Comment by jacobbednarz** [comment]
#246 should fix this oversight for all types of builds
