### ISSUE TITLE
openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by zahidferz** [cloudflare/cf-terraforming#252]
### Confirmation

- [x] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.1.1-dev+11e33de82da2

### Expected outcome

cf-terraforming generate -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_KEY

Expected the terraform code 

### Actual outcome

FATA[0000] unexpected error: openpgp: signature made by unknown entity

### Steps to reproduce

```dockerfile
ARG VERSION=acf7984ed852305f877c703b0a4898d80cc50a89

FROM golang:1.15-alpine AS build

ENV GO111MODULE=on

RUN apk add git \
    && git clone https://github.com/cloudflare/cf-terraforming.git /cf-terraforming \
    && cd /cf-terraforming \
    && go build -o cf-terraforming cmd/cf-terraforming/main.go \
    && cp cf-terraforming /usr/local/bin/cf-terraforming

RUN apk add ca-certificates && update-ca-certificates 
ENTRYPOINT ["/usr/local/bin/cf-terraforming"]
```
``` bash
docker build -t cf-terraforming . 
docker run -it cf-terraforming generate -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_KEY
```

**Comment by blcetux** [comment]
Hi,

I believe that PR #250 should fix this.

Regards

**Comment by jacobbednarz** [comment]
#250 has been merged so few free to try this again
