### ISSUE TITLE
Could not route to /zones/dns_records when trying to generate dns_resources

### ISSUE THREAD

**Issue by fionera** [cloudflare/cf-terraforming#254]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.2.0-dev+ed5b4fff190d

### Expected outcome

Importing the DNS Resources

### Actual outcome

$ cf-terraforming generate --resource-type "cloudflare_record"  -c .cf-terraforming.yaml -vvv
DEBU[0000] initializing cloudflare-go                    account_id= email=user@example.com zone_id=
DEBU[0005] initialising Terraform in .                  
DEBU[0018] reading Terraform schema for Cloudflare provider 
DEBU[0019] beginning to read and build cloudflare_record resources 
FATA[0019] HTTP status 400: Could not route to /zones/dns_records, perhaps your object identifier is invalid? (7003), No route for that URI (7000) 

### Steps to reproduce

1. Use a Config with Mail, Key, Account ID
2. Try to generate DNS Resources
3. Doesnt work

**Comment by jacobbednarz** [comment]
By the looks of that error message, you're not setting the zone ID. You'll need to set it in order to attempt to generate the resources.

**Comment by msiherb** [comment]
@jacobbednarz is correct ... 
I have added the zone_id in the **.cf-terraforming.yaml** and it worked.
```
email: "myname@example.com"
token: "xxxxxxyyyyyzzzz"
account: "xxxxxxyyyyyzzzz"
zone: "xxxxxxyyyyyzzzz"
```

and received the desired response as 

```
resource "cloudflare_record" "terraform_managed_resource_xxxyyyzzz" {
  name    = "www"
  proxied = true
  ttl     = 1
  type    = "CNAME"
  value   = "example.com"
  zone_id = "xxxxxxyyyyyzzzz"
}
```
