### ISSUE TITLE
support mac m1

### ISSUE THREAD

**Issue by camerondavison** [cloudflare/cf-terraforming#256]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.2.0

### Expected outcome

It should generate the terraform resources

### Actual outcome

Fatal Error

### Steps to reproduce

It looks like maybe tfinstall does not work with the mac m1 chip

```
$ cf-terraforming generate
FATA[0000] unexpected error: invalid checksum: no checksum found in: https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_SHA256SUMS
```

**Comment by jacobbednarz** [comment]
I'm afraid this is an issue with M1 compatible builds of Terraform, not our tool. We build and distribute ARM builds of this tool. You'll need to check with the Terraform product for M1 support and why it isn't in the checksum file.
