### ISSUE TITLE
cloudflare_zone object imported with unsupported "status" field

### ISSUE THREAD

**Issue by wolfmd** [cloudflare/cf-terraforming#262]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.3.0

### Expected outcome

The zone resource would be imported using only the supported arguments from https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone 

### Actual outcome

Zone resource generated with a `status` attribute which isn't accepted as an argument

### Steps to reproduce

1.  cf-terraforming generate --account $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_zone"
2. terraform plan should produce output like
```
Error: "status": this field cannot be set

  on tseng_prod.tf line 1, in resource "cloudflare_zone" "terraform_managed_resource_4e88e4d568a508c00ef1fd992efbe5":
   1: resource "cloudflare_zone" "terraform_managed_resource_4e88e4d56877a508c00ef1fd992efbe5" {

```

**Comment by jacobbednarz** [comment]
thanks for spotting this! #263 should fix the generatd output to handle this one.

**Comment by vanmash** [comment]
@jacobbednarz Looks like [the gremlins ](https://en.wikipedia.org/wiki/Gremlins) are back...

1. import
› .\cf-terraforming.exe generate -a <EMAIL> -z <ZONE_ID> --resource-type cloudflare_zone

```yaml
resource "cloudflare_zone" "terraform_managed_resource_<ZONE_ID>" {
  paused = false
  plan = "pro"
  **status = "active"**
  type = "full"
  zone = "simployer.com"
}
```

2. validation (fails)
› terraform.exe validate

```
│ Error: "status": this field cannot be set
│
│   with cloudflare_zone.terraform_managed_resource_<ZONE_ID>,
│   on cloudflare.tf line 1773, in resource "cloudflare_zone" "terraform_managed_resource_<ZONE_ID>":
│ 1773: resource "cloudflare_zone" "terraform_managed_resource_<ZONE_ID>" {
│
```

BTW: this tool is **x100**! Thanks!

**Comment by jacobbednarz** [comment]
It looks like the fix is still in place. Are you definitely running the fixed version?

**Comment by vanmash** [comment]
› .\cf-terraforming.exe version
cf-terraforming v0.3.0

› terraform version
Terraform v1.0.2
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.24.0

**Comment by vanmash** [comment]
Release https://github.com/cloudflare/cf-terraforming/releases/tag/v0.3.0 is dated as 20th May and PR https://github.com/cloudflare/cf-terraforming/pull/263 is from 21st May

Could it be the reason?

**Comment by jacobbednarz** [comment]
Yes, it hasn't been released to a stable release yet. You'll need to run and build master if you want this now.

**Comment by vanmash** [comment]
Thanks. That one could wait :)
