### ISSUE TITLE
Missing required fields in imported resources like cloudflare_load_balancer, cloudflare_waf_package and cloudflare_custom_pages

### ISSUE THREAD

**Issue by danielmayor** [cloudflare/cf-terraforming#264]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.3.0

### Expected outcome

Some resources aren't imported completely, some **required** fields are missing. For example, load balancers look like this:

```
resource "cloudflare_load_balancer" "terraform_managed_resource_" {
  default_pool_ids = <default_pool_ids>
  fallback_pool_id = <fallback_pool_id>
  enabled          = true
  name             = "www.dev.example.com"
  proxied          = true
  session_affinity = "none"
  session_affinity_attributes = {
    samesite = "Auto"
    secure   = "Auto"
  }
  steering_policy = <steering_policy>
  zone_id         = <zone_id>
}
```

### Actual outcome

```
resource "cloudflare_load_balancer" "terraform_managed_resource_" {
  enabled          = true
  name             = "www.dev.example.com"
  proxied          = true
  session_affinity = "none"
  session_affinity_attributes = {
    samesite = "Auto"
    secure   = "Auto"
  }
  steering_policy = <steering_policy>
  zone_id         = <zone_id>
}
```

I didn't have the chance to test every other resource, but many others may be affected because I saw the same issue in at least 2 more:

- **cloudflare_waf_package** does not import **package_id**
- **cloudflare_custom_pages** does not import **url**

### Steps to reproduce

Import an affected _cloudflare_resource_:

1. `cf-terraforming generate --resource-type cloudflare_load_balancer --zone <zone_id> >> resources.tf`
2. `cf-terraforming apply`

If I try to re-deploy it, I get this error:
`│ The argument "fallback_pool_id" is required, but no definition was found.`

or this one:
`│ The argument "default_pool_ids" is required, but no definition was found.`

**Comment by danielmayor** [comment]
Unfortunately I'm not able to provide a reproduction yet, I'm in the first steps of importing the setup of a manual configured account.

**Comment by jacobbednarz** [comment]
i'll take a look at the load balancer issue here however please open individual issues for any othe resources you find so they can be tracked individually.
