### ISSUE TITLE
Error when attempting to retrieve Cloudflare Load Balancer Pool configuration in Terraform using cf-terraforming

### ISSUE THREAD

**Issue by ritesh-harry** [cloudflare/cf-terraforming#266]
Cannot get an export of the load balancer pools in Terraform format. Error as per below,

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}
goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.nestBlocks(0xc000756680, 0xc0004c7ad0, 0x2, 0x0, 0x0)
/cf-terraforming/internal/app/cf-terraforming/cmd/util.go:187 +0x135f
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0x18f8f20, 0xc0001e1d40, 0x0, 0x4)
/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:645 +0x1059
github.com/spf13/cobra.(*Command).execute(0x18f8f20, 0xc0001e1d00, 0x4, 0x4, 0x18f8f20, 0xc0001e1d00)
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x18f9420, 0xc00027ff78, 0x4080c5, 0xc00008a058)
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x31
main.main()
/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x25

I am using Docker Desktop for Windows. This is the Docker command I am running,

docker run -it --env CLOUDFLARE_EMAIL=<email_address_here>--env CLOUDFLARE_API_KEY=<global_api_key_here> --env CLOUDFLARE_ACCOUNT_ID=<CF_accountid_here> -v c:/docker:/cloudflare --workdir=/cloudflare cfterraforming generate --resource-type cloudflare_load_balancer_pool --zone <CF_zoneid_here> >> cloudflare.tf

An example, I am able to run the same command above and replace cloudflare_load_balancer_pool with cloudflare_load_balancer_monitor which works fine and I can retrieve the load balancer monitors.

The Docker file I used to create the image is as per below,

FROM golang:1.15-alpine AS build
ENV GO111MODULE=on
RUN apk add git \
&& git clone https://github.com/cloudflare/cf-terraforming.git /cf-terraforming \
&& cd /cf-terraforming \
&& go build -o cf-terraforming cmd/cf-terraforming/main.go
FROM alpine:3
RUN apk add ca-certificates && update-ca-certificates
COPY --from=build /cf-terraforming/cf-terraforming /usr/local/bin/cf-terraforming
ENTRYPOINT ["/usr/local/bin/cf-terraforming"]

Using the Docker image created from the file I am able to retrieve different resource configurations in Terraform format usinf cf-terraforming. It seems, for now, it is just the cloudflare_load_balancer_pool which is giving an error.

**Comment by jacobbednarz** [comment]
have you attempted this with the latest released version? in future, please use the [bug report template](https://github.com/cloudflare/cf-terraforming/issues/new?assignees=&labels=kind%2Fbug%2Cneeds-triage&template=bug.yml) for filing issues to speed up the triage process.

**Comment by ritesh-harry** [comment]
Hi,

Thank you for the response. I have not tried with the latest version yet, I will give it a try and update. Apologies for the wrong issue type raised. I was just given the link by Cloudflare support and asked to raise an issue.

Thanks.

**Comment by ritesh-harry** [comment]
Hi,

I tried golang 1.16.5-alpine and alpine 3.13. I am assuming the latest version of cf-terraforming will be utilized, are you able to confirm? Got a similar error, maybe the same error, when trying to retrieve the load balancer pool configuration but for other resources e.g. dns records & load balancer monitors it works ok.

Thanks.

Docker file as per below,

FROM golang:1.16.5-alpine AS build
ENV GO111MODULE=on

RUN apk add git \
    && git clone https://github.com/cloudflare/cf-terraforming.git /cf-terraforming \
    && cd /cf-terraforming \
    && go build -o cf-terraforming cmd/cf-terraforming/main.go
	
FROM alpine:3.13
RUN apk add ca-certificates && update-ca-certificates
COPY --from=build /cf-terraforming/cf-terraforming /usr/local/bin/cf-terraforming
ENTRYPOINT ["/usr/local/bin/cf-terraforming"]

Error as per below,

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.nestBlocks(0xc0005cd400, 0xc00065bbc0, 0x2, 0xc00003e5d0, 0x30)
	/cf-terraforming/internal/app/cf-terraforming/cmd/util.go:187 +0x131f
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0x14c0de0, 0xc000185c40, 0x0, 0x4)
	/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:645 +0x1059
github.com/spf13/cobra.(*Command).execute(0x14c0de0, 0xc000185c00, 0x4, 0x4, 0x14c0de0, 0xc000185c00)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x14c12e0, 0xc0002dff78, 0x4080e5, 0xc00008a058)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
	/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x31
main.main()
	/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x25

**Comment by jacobbednarz** [comment]
latest released version of **cf-terraforming** 🙂

**Comment by ritesh-harry** [comment]
Thank you. Do you happen to know how I can reference the latest version of cf-terraforming in a docker file? Or if you have any working docker file examples I can try?

Thanks.

**Comment by jacobbednarz** [comment]
you can download the precompiled executables at https://github.com/cloudflare/cf-terraforming/releases/tag/v0.3.0 or target the v0.3.0 tag in your git clone command.

**Comment by ritesh-harry** [comment]
Hi,

I've got cf-terraforming working in a cmd prompt on Windows. The documentation available online to get it working is not very clear. Anyways, I'm using the latest version now. cf-terraforming version details as per below,

C:\cf-terraforming> .\cf-terraforming.exe version
-
cf-terraforming v0.3.0

I still get an error when trying to get an export of the load balancer pools. I have tried other resources e.g. dns records and load balancer monitors and that works ok.

Thanks.

Error as per below,

time="2021-06-10T20:21:54+10:00" level=debug msg="initializing cloudflare-go" account_id=<account_id_displayed_here> email=<email_displayed_here>  zone_id=
time="2021-06-10T20:21:54+10:00" level=debug msg="configuring Cloudflare API with account" account_id=<account_id_displayed_here>
time="2021-06-10T20:23:01+10:00" level=debug msg="initialising Terraform in ."
time="2021-06-10T20:23:20+10:00" level=debug msg="reading Terraform schema for Cloudflare provider"
time="2021-06-10T20:23:21+10:00" level=debug msg="beginning to read and build cloudflare_load_balancer_pool resources"
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.nestBlocks(0xc000234e00, 0xc000665830, 0x2, 0xc000577890, 0x30)
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/util.go:187 +0x131f
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0x14ff940, 0xc00044a2d0, 0x0, 0x9)
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:644 +0xfe5
github.com/spf13/cobra.(*Command).execute(0x14ff940, 0xc00044a240, 0x9, 0x9, 0x14ff940, 0xc00044a240)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x14ffe40, 0xc0002dff78, 0x41670b, 0xc00003a0b8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x38
main.main()
        /home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x27

**Comment by jacobbednarz** [comment]
> Just thought I'd ask this question - has cf-terraforming been tested with the Cloudflare load balancer pools to check if it actually works and can export the resources?

Yep, see https://github.com/cloudflare/cf-terraforming/tree/master/testdata. It asserts based on the API response _and_ expected Terraform output. Are you able to provide your API response for this request? It doesn't have to be through the cf-terraforming tool if you're able to just curl the endpoint instead and get the response we need.

**Comment by ritesh-harry** [comment]
Hi,

If I use Postman I can query the endpoint and receive a 200 OK. Please see sample data below. There would be more than one entry as we have multiple load balancer pools but same config blocks etc as the sample shown below.

Thanks.

{
    "result": [
        {
            "description": "",
            "created_on": "2021-05-04T01:13:36.238043Z",
            "modified_on": "2021-06-08T12:00:04.795719Z",
            "id": "pool_id_here",
            "enabled": true,
            "minimum_origins": 1,
            "monitor": "monitor_id_here",
            "name": "pool_name_here",
            "notification_email": "notification_email_here",
            "check_regions": [
                "OC"
            ],
            "notification_filter": {
                "pool": {}
            },
            "healthy": true,
            "origins": [
                {
                    "name": "F5",
                    "address": "ip_address_here",
                    "enabled": true,
                    "weight": 0,
                    "header": {
                        "Host": [
                            "host_name_here"
                        ]
                    },
                    "healthy": true,
                    "failure_reason": "No failures"
                },
                {
                    "name": "Kemp",
                    "address": "ip_address_here",
                    "enabled": true,
                    "weight": 1,
                    "header": {
                        "Host": [
                            "host_name_here"
                        ]
                    },
                    "healthy": true,
                    "failure_reason": "No failures"
                }
            ]
        }|
 ],
  "success": true,
  "errors": [],
  "messages": []
}

**Comment by jacobbednarz** [comment]
Thanks, I'll see if I can use that to force the failure.

**Comment by ritesh-harry** [comment]
Thank you.

I have encountered another issue when trying to create a Cloudflare load balancer pool with Terraform. I referenced the documentation online on how to create a load balancer pool using Terraform. It seems to not like the header block in the origins section.

Link -  
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/load_balancer_pool#argument-reference

I'm using Terraform v1.0.0 (have tried 0.15.x as well and get same error) and provider registry.terraform.io/cloudflare/cloudflare v2.18.0.

Error as per below,

terraform validate

 Error: Unsupported block type

   on loadbalancer-pools.tf line 6, in resource "cloudflare_load_balancer_pool" "pool":
    6:     header {

 Blocks of type "header" are not expected here.


 Error: Unsupported block type

   on loadbalancer-pools.tf line 16, in resource "cloudflare_load_balancer_pool" "pool":
   16:     header {

 Blocks of type "header" are not expected here.

**Comment by jacobbednarz** [comment]
please open a separate issue in the Terraform provider if it's occurring outside of cf-terraforming. there is an issue template there that will request information.

**Comment by ritesh-harry** [comment]
Hi,

Sure, will do.

Thanks.

**Comment by ritesh-harry** [comment]
Hi,

Any updates?

Thanks.

**Comment by jacobbednarz** [comment]
Not from me. I suspect it's to do with the HTTP host header overrides
though as that seems to be the only difference in the testdata and this
payload. It's also relatively new so may not yet be fully vetted in this
tool.

**Comment by ritesh-harry** [comment]
Hi,

Ok thanks. Is it worth leaving this request open? Will the issue still be looked into? It would be useful to get cf-terraforming working to retrieve the load balancer pool resource configuration with different config compared to the test data.

Thanks.

**Comment by mcmcghee** [comment]
Ran into this same error today trying to generate with cloudflare_load_balancer_pool.

`panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.nestBlocks(0xc0005375c0, 0xc0004f08a0, 0x2, 0xc000876900, 0x34)
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/util.go:187 +0x131f
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0x20bbce0, 0xc0004ac1e0, 0x0, 0x6)
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:644 +0xfc5
github.com/spf13/cobra.(*Command).execute(0x20bbce0, 0xc0004ac180, 0x6, 0x6, 0x20bbce0, 0xc0004ac180)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x20bc1e0, 0xc00035ff78, 0x1006045, 0xc000108058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x31
main.main()
        /home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x25`

**Comment by wwwlde** [comment]
Still not working correctly :-(

```
$ cf-terraforming generate --resource-type "cloudflare_load_balancer_pool" --account $CLOUDFLARE_ACCOUNT_ID -z $CLOUDFLARE_ZONE_ID > cloudflare_load_balancer_pool.tf
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.nestBlocks(0xc000549b80, 0xc001994a20, 0x2, 0xc0012cf7a0, 0x30)
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/util.go:187 +0x131f
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0x14c4e20, 0xc00050c180, 0x0, 0x6)
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:644 +0xfc5
github.com/spf13/cobra.(*Command).execute(0x14c4e20, 0xc00050c120, 0x6, 0x6, 0x14c4e20, 0xc00050c120)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x14c5320, 0xc0002dff78, 0x407fe5, 0xc000038178)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x31
main.main()
	/home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x25
```

**Comment by mcmcghee** [comment]
Still an issue
