### ISSUE TITLE
Terraform issue when using M1 Mac and forcing x86-64 mode for stability

### ISSUE THREAD

**Issue by bourbonfgiles** [cloudflare/cf-terraforming#276]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming generate --resource-type "cloudflare_record" -z "ACTUAL ID REMOVED" -k $CLOUDFLARE_API_KEY -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL --verbose --terraform-install-path '/Opt/homebrew/Cellar/tfenv/2.2.2/bin/terraform'

### Expected outcome

A record being created.

### Actual outcome

FATA[0000] unexpected error: invalid checksum: no checksum found in: https://releases.hashicorp.com/terraform/1.0.1/terraform_1.0.1_SHA256SUMS

### Steps to reproduce

Using an M1 Mac, with Terraform installed via Brew, and forced to use x86-64 mode for stability.

**Comment by jacobbednarz** [comment]
I'm afraid this is something you'll need to contact Hashicorp about as they manage the checksum files for Terraform. 

Also, `terraform-install-path` is being used incorrectly. It is intended to be the directory where your Terraform configuration lives (and subsequently gets initialised), not the path to the binary. Most people will not need this flag.

**Comment by bourbonfgiles** [comment]
@jacobbednarz I got this to work by downloading darwin64 version of cf-terraforming and ran it with arch -x86_64 which caused it to pull the darwin64 version of terraform and work. Might be a useful workaround for other M1 users?
