### ISSUE TITLE
403: Authentication error (10000) with cloudflare_load_balancer_monitor

### ISSUE THREAD

**Issue by danielmayor** [cloudflare/cf-terraforming#279]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.3.0

### Expected outcome

I am running several _cf-terraforming generate_ commands against my Cloudflare account.

Some of them work fine:
**cf-terraforming generate --resource-type "cloudflare_load_balancer" -z $ZONE**
```
resource "cloudflare_load_balancer" "terraform_managed_resource_*****" {
  enabled = true
  name = "api.example.com"
  proxied = true
  session_affinity = "none"
  session_affinity_attributes = {
    samesite = "Auto"
    secure = "Auto"
  }
  steering_policy = "geo"
}
```

### Actual outcome

Others don't:

% cf-terraforming generate --resource-type "**cloudflare_load_balancer_monitor**" -z $ZONE
`FATA[0014] HTTP status 403: Authentication error (10000)
`

% cf-terraforming generate --resource-type "**cloudflare_load_balancer_pool**" -z $ZONE
`FATA[0013] HTTP status 403: Authentication error (10000)
`

### Steps to reproduce

I am using same API Token for every import. I can see and edit everything with my user in the UI.

Same issue when I use `cf-terraforming import` though Load Balancer related resources import is not yet supported.

Token permissions:
- Zone Settings:Edit
- Zone:Edit
- Workers Routes:Edit
- SSL and Certificates:Edit
- Page Rules:Edit
- Load Balancers:Edit
- Firewall Services:Edit
- DNS:Edit

### References

https://github.com/cloudflare/cf-terraforming/issues/180

**Comment by jacobbednarz** [comment]
What is the result if you use an API key instead?

**Comment by danielmayor** [comment]
If I use an API key It doesn't work for me:

% _cf-terraforming generate --resource-type "cloudflare_load_balancer" -z $CLOUDFLARE_ZONE_ID_
`FATA[0007] configuration is invalid`

If I use it with **import** and another resource (cloudflare_record) it works fine:

% _cf-terraforming import --resource-type "cloudflare_record" -z $CLOUDFLARE_ZONE_ID_
`terraform import cloudflare_record.terraform_managed_resource_f6e78519bc1ee41d071b2b788eb64422 92983eb58 zone_id/cloudflare_record_id`

Same issue with **generate** on _cloudflare_record_:
% _cf-terraforming generate --resource-type "cloudflare_record" -z $CLOUDFLARE_ZONE_ID_
`FATA[0007] configuration is invalid`

**Comment by jacobbednarz** [comment]
As I mentioned in #264, can you please open **individual issues per resource**, don't lump them together. In your individual reports, you can also provide the verbose output which may provide further hints as to what is happening. 

If the API key doesn't work, there is something incorrect with your Cloudflare permissions or the zones/resources you are targeting.

**Comment by danielmayor** [comment]
Thanks, Jacob. Please let's focus on _cloudflare_load_balancer_monitor_ resource.

I think that Token permissions are right:
**Load Balancers:Edit**

And I am running an Administrator account so the API key should be good.

I ran it again with verbose flag, see the difference:

% _cf-terraforming generate --resource-type "cloudflare_load_balancer_monitor" -z $ZONE_
`FATA[0014] HTTP status 403: Authentication error (10000)`

% _cf-terraforming generate --resource-type "cloudflare_load_balancer_monitor" -z $ZONE **-v**_
```
DEBU[0000] initializing cloudflare-go with API Token     account_Id=<account_id> zone_id=<zone_id>
DEBU[0000] configuring Cloudflare API with account       account_id=<account_id>
DEBU[0009] initialising Terraform in .
DEBU[0012] reading Terraform schema for Cloudflare provider
DEBU[0014] beginning to read and build cloudflare_load_balancer_monitor resources
FATA[0015] HTTP status 403: Authentication error (10000)
```

**Comment by jacobbednarz** [comment]
It looks like the there are two issues here tangentially related.

The first is that there isn't a **zone level** `cloudflare_load_balancer_monitor` resource. The resources are either created at the user level (`/user`) or account level (`/accounts/.../load_balancers/monitors`). Which leads us to the second issue; out of the box, you're attempting to query the user level resources which your token permissions wouldn't allow.

If you provide the `--account` parameter to your command, it should work as expected* (providing you don't have new-ish configuration parameters outlined in #266 which isn't supported yet).
