### ISSUE TITLE
clouflare_custom_pages is not yet supported for automatic generation

### ISSUE THREAD

**Issue by danielmayor** [cloudflare/cf-terraforming#280]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.3.0

### Expected outcome

According to the documentation, _clouflare_custom_pages_ is supported for both `generate` and `import` commands.

### Actual outcome

I am getting this error:

% _cf-terraforming generate --resource-type "clouflare_custom_pages" -z $ZONE_
`"clouflare_custom_pages" is not yet supported for automatic generation%`

### Steps to reproduce

I tried both API Key and API Token and I get same error.

The user has Administrator role in Cloudflare and it works for other resources.

**Comment by danielmayor** [comment]
I was able to grab the config through the API: `curl https://api.cloudflare.com/client/v4/zones/$ZONE/custom_pages`

Now I believe that issue here is that the message error is not accurate because I have no Custom Pages created yet.

**Comment by jacobbednarz** [comment]
you have a typo in your command; "clouflare_custom_pages" should be "cloudflare_custom_pages"
