### ISSUE TITLE
cloudflare_certificate_pack - unexpected type "universal"

### ISSUE THREAD

**Issue by vanmash** [cloudflare/cf-terraforming#284]
### Confirmation

- [x] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.3.0

### Expected outcome

correctly generated resource definition

### Actual outcome

› .\cf-terraforming.exe generate -a EMAIL -z ZONE_ID --resource-type cloudflare_certificate_pack
```yaml
resource "cloudflare_certificate_pack" "terraform_managed_resource_ID" {
  hosts = [ "*.XXXXX.com", "XXXXX.com" ]
  type = "universal"
}
```

› terraform.exe validate
```
│ Error: expected type to be one of [custom dedicated_custom advanced], got universal
│
│   with cloudflare_certificate_pack.terraform_managed_resource_ID,
│   on cloudflare.tf line 22, in resource "cloudflare_certificate_pack" "terraform_managed_resource_ID":
│   22: resource "cloudflare_certificate_pack" "terraform_managed_resource_ID" {
│
```

### Steps to reproduce

1. .\cf-terraforming.exe generate -a EMAIL -z ZONE --resource-type cloudflare_certificate_pack
2. terraform validate

### References
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack#type

_No response_

**Comment by vanmash** [comment]
`"type": "universal"` is shown in the `terraform.tfstate` (after `import`) and in the cloudflare portal itself.

```json
{
  "version": 4,
  "terraform_version": "1.0.2",
  "serial": 184,
  "lineage": "XXXXX",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "cloudflare_certificate_pack",
      "name": "terraform_managed_resource_XXXXX",
      "provider": "provider[\"registry.terraform.io/cloudflare/cloudflare\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "certificate_authority": null,
            "cloudflare_branding": null,
            "hosts": [
              "*.XXXXX.com",
              "XXXXX.com"
            ],
            "id": "XXXXX",
            "type": "universal",
            "validation_method": null,
            "validity_days": null,
            "zone_id": "XXXXX"
          },
          "sensitive_attributes": [],
          "private": "XXXXX=="
        }
      ]
    },
```
@jacobbednarz could you please take a look? Do you need anything from my side?

**Comment by jacobbednarz** [comment]
universal certificates cannot be managed by customers. i'd suggest you just ignore this as a resource for now and we skip them in a future step.
