### ISSUE TITLE
Certain resources types (filter/firewall_rule) not pulling zone_id

### ISSUE THREAD

**Issue by buttersausage** [cloudflare/cf-terraforming#285]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.3.0

### Expected outcome

cf-terraforming generate command for filter/firewall_rule pulls the tf contents including the the zone_id entry.

### Actual outcome

cf-terraforming generate command for filter/firewall_rule pulls the tf contents but is missing the zone_id entry.

### Steps to reproduce

Run: 

```
cf-terraforming generate --account ID --email EMAIL --key SUPERADMINKEY --resource-type cloudflare_filter --zone ZONE_ID -v
cf-terraforming generate --account ID --email EMAIL --key SUPERADMINKEY --resource-type cloudflare_firewall_rule --zone ZONE_ID -v
```

Starts pulling values, and outputs these errors in the progress:

```
DEBU[0010] got unknown attribute configuration: key products, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key zone_id, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key priority, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key products, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key zone_id, value <nil>, value type <nil> 
```

TF output is fine but is missing the zone_id entry within the resource in the .tf output, in turn terraform plan/apply fail because Cloudflare requires the zone_id entry

**Comment by jacobbednarz** [comment]
You don't need to pass account ID _and_ zone ID. Try setting one or the other based on the resource you wish to export.

**Comment by buttersausage** [comment]
It still doesn't work. I tried remove the zone id, leaving just account id and got 

```
DEBU[0008] beginning to read and build cloudflare_firewall_rule resources 
no resources found to generate. Exiting...%  
```

Tried also removing account id and just using zone_id and the output is still missing the zone_id:

```
DEBU[0008] reading Terraform schema for Cloudflare provider 
DEBU[0008] beginning to read and build cloudflare_firewall_rule resources 
DEBU[0010] got unknown attribute configuration: key products, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key zone_id, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key priority, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key products, value <nil>, value type <nil> 
DEBU[0010] got unknown attribute configuration: key zone_id, value <nil>, value type <nil> 
resource "cloudflare_firewall_rule" "terraform_managed_resource_zzzzzzzzzzzz" {
  action = "block"
  description = "zzzzzzzzzzzz"
  filter_id = "zzzzzzzzzzzz"
  paused = false
  priority = 1000
}

resource "cloudflare_firewall_rule" "terraform_managed_resource_xxxxxxxxxxx" {
  action = "block"
  description = "xxxxxxxxxxx"
  filter_id = "xxxxxxxxxxx"
  paused = false
}
```

**Comment by jacobbednarz** [comment]
what commands after you running for the zone level resources?

**Comment by buttersausage** [comment]
`cf-terraforming generate --email EMAIL --key SUPERADMINKEY --resource-type cloudflare_firewall_rule --zone ZONE_ID -v`

**Comment by jacobbednarz** [comment]
that command is working here and in the test suite so something else is up. can you supply the HTTP request/response being performed by cf-terraforming? you'll need a MITM proxy tool such as Proxyman or Charles.

**Comment by buttersausage** [comment]
Is there any proxy switch i need to use for cf-terraforming? As its not showing up on either mitm tools

**Comment by n0madic** [comment]
I also have many generated resources do not contain the required **zone_id**, if I make a regular request with a curl (`GET zones/:zone_identifier/filters`), then there is also no necessary attribute there
```
{
  "result": [
    {
      "id": "be879655f0244e19bad98fcfd5782a14",
      "paused": false,
      "expression": "(ip.src in {8.8.8.8})"
    },
...
```
however, as well as in the [documentation](https://api.cloudflare.com/#filters-list-filters)

**Comment by n0madic** [comment]
[The following resources now require Zone IDs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-2-upgrade#zone-name-to-zone-id-changes):
`cloudflare_access_rule`
`cloudflare_filter`
`cloudflare_firewall_rule`
`cloudflare_load_balancer`
`cloudflare_page_rule`
`cloudflare_rate_limit`
`cloudflare_record`
`cloudflare_waf_rule`
`cloudflare_worker_route`
`cloudflare_zone_lockdown`
`cloudflare_zone_settings_override`

But only `cloudflare_record` is OK
