### ISSUE TITLE
cloudflare_certificate_pack -- cannot unmarshal string into Go struct

### ISSUE THREAD

**Issue by bulnv** [cloudflare/cf-terraforming#288]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.3.0

### Expected outcome

certificate pack terraform code with edge advanced certificates

### Actual outcome

`FATA[0018] error unmarshalling the JSON response: json: cannot unmarshal string into Go struct field CertificatePack.result.primary_certificate of type int`

### Steps to reproduce

1. `export CLOUDFLARE_ACCOUNT_ID=val && export CLOUDFLARE_API_TOKEN='val' && export CLOUDFLARE_EMAIL = 'val`
2. `cf-terraforming generate --account $CLOUDFLARE_ACCOUNT_ID --resource-type cloudflare_certificate_pack -z $ZONE`

**Comment by jacobbednarz** [comment]
this was an issue with the terraform provider; if you're running [v2.25.0](https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v2.25.0) this should be fixed
