### ISSUE TITLE
CF Terraforming returning SIGSEGV Error

### ISSUE THREAD

**Issue by WoodProgrammer** [cloudflare/cf-terraforming#289]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.3.0

### Expected outcome

Hi everyone,

I've tried to run cf-terraforming command in github-actions but application is returning nil pointer and segmentation fault errors.

### Actual outcome

That's the results of DEBUG logs ,

```
time="2021-08-13T14:14:04Z" level=debug msg="initialising Terraform in ."
time="2021-08-13T14:14:05Z" level=debug msg="reading Terraform schema for Cloudflare provider"
time="2021-08-13T14:14:05Z" level=debug msg="beginning to read and build cloudflare_record resources"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x70a397]
```

I'm working on ubuntu-latest image it is still returning this error to me even different providers and CI servers I did not faced that issue while running cf-terraforming.

Thanks

### Steps to reproduce

Run cf-terraforming on github-actions

**Comment by jacobbednarz** [comment]
This isn't an issue with GitHub Actions or a specific CI provider, it's to do with your configuration. Can you please provide the HTTP interactions that are happening using a MITM tool so we can dig into the cause here?

**Comment by n0madic** [comment]
Many CI/CD systems (GitHub Actions, GitLab CI etc) set the environment variable `CI=true`, which is [hardcoded](https://github.com/cloudflare/cf-terraforming/blob/9f47d9fe42f88cffcc1bbf5cc361508e7a14aa2c/internal/app/cf-terraforming/cmd/util.go#L107) in this utility and disables the initialization of the API client.
I think you need to change this variable to something more original or change the approach to testing.

**Comment by jacobbednarz** [comment]
@n0madic please open your own discussion issue if you wish to pursue it; this is unrelated and detracts from the initial report.

**Comment by n0madic** [comment]
Oh why, I had the same error in Gitlab CI and spent a lot of time fixing it...
Temporary workaround:
`unset CI`
before launch cf-terraforming in CI/CD

**Comment by jacobbednarz** [comment]
What is your use case for running this in a CI environment? It's intended as a one off to run locally to commit changes to a VCS and from there, use Terraform core to apply future changes.

**Comment by n0madic** [comment]
We use it to periodically export CF settings, something like a backup

**Comment by jacobbednarz** [comment]
I'd strongly discourage using this for that. Instead, run a drift detection using `terraform plan` (for resource changes using the state) and query the API for differences in unmanaged resources. 

This tool is intended as a one time dump and state import, anything outside of that at this point is beyond the scope of expected usage.

**Comment by n0madic** [comment]
I agree with this approach, but at the moment this is the best solution for us.
If you don't touch the `CI` variable, please make an obvious error message instead of SIGSEGV.
