### ISSUE TITLE
Getting set up: FATA[0007] configuration is invalid

### ISSUE THREAD

**Issue by robertlagrant** [cloudflare/cf-terraforming#294]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.3.0

### Expected outcome

I'm running the sample `cf-terraforming generate` command from the Github documentation. Expecting to see the first resource type (cloudflare_record) appear in output.

### Actual outcome

```FATA[0007] configuration is invalid```

The above is output. I've also had an 8 and a 9.

### Steps to reproduce

1. Install cf-terraforming on MacOS with `brew install cask`
2. Set up an API token in the Cloudflare web UI
3. Create a cloudflare.tf file with the following contents:
    ```
    provider 'cloudflare' {
     # Cloudflare email saved in $CLOUDFLARE_EMAIL
     # Cloudflare API token saved in $CLOUDFLARE_API_TOKEN
    }
    ```
4. run `cf-terraforming generate -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_TOKEN --resource-type "cloudflare_record"`

**Comment by jacobbednarz** [comment]
You need a working and initialised Terraform directory for this to operate. I suspect it's the fact you're not configuring the provider block correctly. Can you try setting that with static values or using Terraform variables (the ones you're using are not automatically passed into Terraform itself).

**Comment by robertlagrant** [comment]
@jacobbednarz thank you; that was the clue I needed. The `.tf` file was invalid.
