### ISSUE TITLE
"" is not yet supported for automatic generation

### ISSUE THREAD

**Issue by robertlagrant** [cloudflare/cf-terraforming#301]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.3.0

### Expected outcome

Retrieve worker routes as Terraform HCL.

### Actual outcome

`"" is not yet supported for automatic generation`

### Steps to reproduce

1. Run `cf-terraforming generate -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_TOKEN all`

**Comment by robertlagrant** [comment]
When running with `-v`:

```
% cf-terraforming generate -v -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_TOKEN all
DEBU[0000] initializing cloudflare-go                    account_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx email=x@y.com zone_id=
DEBU[0000] configuring Cloudflare API with account       account_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0009] initialising Terraform in .
DEBU[0009] reading Terraform schema for Cloudflare provider
DEBU[0009] beginning to read and build  resources
"" is not yet supported for automatic generation%
```

**Comment by jacobbednarz** [comment]
You need to provide a resource type to export. See the example usage in the [README](https://github.com/cloudflare/cf-terraforming/blob/master/README.md) as well as the supported resources table below it.

**Comment by jacobbednarz** [comment]
v0.4.0 tightens the validation for `generate` commands so that should point this issue out to you earlier now.

**Comment by robertlagrant** [comment]
As soon as Brew notices it I'll give it a whirl!
