### ISSUE TITLE
FATA[0010] HTTP status 400: Invalid request headers (6003)

### ISSUE THREAD

**Issue by robertlagrant** [cloudflare/cf-terraforming#303]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.4.0

### Expected outcome

Command retrieves terraform syntax for my zone information.

### Actual outcome

```
% cf-terraforming generate -v -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_TOKEN -z zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz --resource-type cloudflare_zone

DEBU[0000] initializing cloudflare-go                    account_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx email=x@y.com zone_id=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
DEBU[0000] configuring Cloudflare API with account       account_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DEBU[0007] initialising Terraform in .
DEBU[0007] reading Terraform schema for Cloudflare provider
DEBU[0007] beginning to read and build cloudflare_zone resources
FATA[0008] HTTP status 400: Invalid request headers (6003)
%
```

### Steps to reproduce

1. Run `cf-terraforming generate -v -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL -k $CLOUDFLARE_API_TOKEN -z zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz --resource-type cloudflare_zone`

**Comment by jacobbednarz** [comment]
Using API tokens, you don't provide the email associated with the account.

**Comment by jacobbednarz** [comment]
If that doesn't change the issue, please provide a dump of the HTTP request/responses using a MITM proxy to see where the error response is coming from.

**Comment by robertlagrant** [comment]
Yes, and also I provided `-k` instead of `-t`. I have started retrieving resources! Crazy users breaking your CLI validation.

![user_testing](https://user-images.githubusercontent.com/1766161/131637065-e472032f-5904-46be-90af-1c0e7e34a5ff.gif)

**Comment by jacobbednarz** [comment]
Ahh, so it was actually that you provided a token format for the key header. The validation message is a little cryptic but good to know you got it sorted.
