### ISSUE TITLE
macOS: "cf-terraforming" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by mw866** [cloudflare/cf-terraforming#309]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.4.0

### Expected outcome

To be able to run the command on macOS

### Actual outcome

```
$ cf-terraforming
[1]    22928 killed     cf-terraforming
```
<img width="261" alt="Screenshot 2021-09-14 at 3 30 38 PM" src="https://user-images.githubusercontent.com/21157769/133214936-3eb09365-960b-42f0-aa73-6a25ec9b9a24.png">

### Steps to reproduce

1. Follow the installation steps 
```
$ brew tap cloudflare/cloudflare
$ brew install --cask cloudflare/cloudflare/cf-terraforming
```

2. Run any  `cf-terraforming` command

### References

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
```

**Comment by jacobbednarz** [comment]
Thanks, this is already on our radar internally to fix. I don't have an ETA or any other updates to share at this point. 

In the meantime, you can hit cancel on that prompt, navigate to the Security and Privacy tab in system preferences and you'll be able to manually allow it to run.

**Comment by nathanclevenger** [comment]
Is there any workaround for this?  I am not able to actually run “cf-terraforming” because of this error.

**Comment by pedrocabido** [comment]
Hi, I've found the same issue:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/63248178/198566489-a3d00714-9791-436f-b378-861df3b2b4ce.png">

```
sw_vers
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```
```
brew info cf-terraforming
==> cf-terraforming: 0.8.4
https://github.com/cloudflare/cf-terraforming
/opt/homebrew/Caskroom/cf-terraforming/0.8.4 (4 files, 9.9MB)
From: https://github.com/cloudflare/homebrew-cloudflare/blob/HEAD/Casks/cf-terraforming.rb
==> Name
cf-terraforming
==> Description
cf-terraforming is a command line utility to facilitate terraforming your existing Cloudflare resources
==> Artifacts
cf-terraforming (Binary)
```

**Comment by florianmutter** [comment]
Any updates here? I have the same issue :(

**Comment by daniloteodoro** [comment]
Same :/

**Comment by doubleforte** [comment]
Same.

**Comment by jacobbednarz** [comment]
this should be solved now. you will need to uninstall and the install the updated formula (not cask).
