### ISSUE TITLE
FATA[0003] failed to detect provider installation 

### ISSUE THREAD

**Issue by tolidano** [cloudflare/cf-terraforming#310]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.4.0

### Expected outcome

file has TF in it

### Actual outcome

error message above

### Steps to reproduce

 cf-terraforming generate -a ACCOUNT -e MY_EMAIL -t MY_KEY --resource-type "cloudflare_record" >> cloudflare_record.tf

when I do this with an older version it works:

 cf-terraforming -a ACCOUNT -e MY_EMAIL -t MY_KEY record >> cloudflare_record.tf

**Comment by jacobbednarz** [comment]
You need a working and initialised Terraform directory for this to operate. I suspect you haven't run `terraform init` in the directory you're attempting to write the configuration out to. By the looks of your command, you've upgraded from a very old version of `cf-terraforming`. I'd recommend familiarising yourself again with the README as quite a bit has changed.

Side note, you don't need `-e` (email) when using `-t`.

**Comment by tolidano** [comment]
https://github.com/cloudflare/cf-terraforming/blob/v0.4.0/README.md

Can you tell me where it talks about terraform init in that readme? The word init does not appear anywhere. Is there somewhere else I should be looking for complete documentation than the readme?

**Comment by jacobbednarz** [comment]
`cf-terraforming` assumes a working and initialised Terraform environment as it fetches the schema from the provider itself unlike the older version that used templates. If the provider isn't able to be used, as you've encountered here, you'll get a fatal error because it doesn't know about the resources. You're welcome to raise PR making the suggestion to add this to the README prerequisites if you'd find it helpful.

**Comment by jefimm** [comment]
it would be very nice to have a guide for the task on just backing up the account configuration without having to go through that errand.
doing the init for the docker does not work with cf-terraforming

```
% cat main.tf
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2.13.0"
    }
  }
}

provider "docker" {}

resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginx" {
  image = docker_image.nginx.latest
  name  = "tutorial"
  ports {
    internal = 80
    external = 8000
  }
}
```


`terraform init

cf-terraforming generate .... leads to 
FATA[0037] failed to detect provider installation

**Comment by mvasilenko** [comment]
@tolidano did you manage to get it work? I've got the same error `FATA[0010] failed to detect provider installation`

**Comment by tolidano** [comment]
I did not, haven’t tried recently, may give it another go with latest, will report back

**Comment by janto** [comment]
Found the issue. The readme really should mention or link to all the required steps explained at https://blog.cloudflare.com/cloudflares-partnership-with-hashicorp-and-bootstrapping-terraform-with-cf-terraforming/

Specifically, the terraform config needs to be:
```
terraform {
    required_providers {
        cloudflare = {
            source = "cloudflare/cloudflare"
        }	
    }
}

provider "cloudflare" {
# api_token  = ""  ## Commented out as we are using an environment var
}
```

After running `terraform init`, I no longer get the error.

**Comment by glensc** [comment]
Thanks @janto! I wasted 30-40 minutes until I found your answer, Submitted it to readme:
- https://github.com/cloudflare/cf-terraforming/pull/725
