### ISSUE TITLE
Bring consistency in authentication between python-cloudflare and cf-terraforming

### ISSUE THREAD

**Issue by chris-zenfolio** [cloudflare/cf-terraforming#315]
### Current `cf-terraforming` version

0.4.0

### Description

The authentication methods for this project rely on a yaml file, environment variables, command-line arguments, and/or a config file.

The Cloudflare project `clouodflare-python` project has a different set of authentications, including environment variables, a config file and passing arguments when defining the class.

REQUEST:  Please modify this project to match the authentication methods described here: https://github.com/cloudflare/python-cloudflare#providing-cloudflare-username-and-api-key

This benefits everyone by having consistency and reduces the security risk by limiting the number of places passwords are stored on the filesystem.

Even if you choose not to follow the cloudflare-python scheme, at least have the discussions so both projects (and any other projects) can benefit from a unified method of authentication.

### Use cases

Having a unified authentication scheme for all of the projects.

### Potential `cf-terraforming` usage

See https://github.com/cloudflare/python-cloudflare#providing-cloudflare-username-and-api-key

### References

https://github.com/cloudflare/python-cloudflare#providing-cloudflare-username-and-api-key

**Comment by jacobbednarz** [comment]
Thanks for raising this but we've made a conscious effort in other tools like the Golang SDK and Terraform to use the `CLOUDFLARE_` for explicitness and to get away from other tools that use a `CF_` prefix.

**Comment by chris-zenfolio** [comment]
At least honor the request by having the discussion with the other teams (as stated in the last line).  The bigger issue is having a UNIFIED authentication style.  Who knows, the other project may choose to follow your implementation.  Don't just shut down the ticket without at least acknowledging the validity of the concern and showing willingness to have the discussions.
