### ISSUE TITLE
Can't import cloudflare_healthcheck

### ISSUE THREAD

**Issue by barrigas** [cloudflare/cf-terraforming#327]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.5.0

### Expected outcome

Import opperation should import the generated tf.

### Actual outcome

`cf-terraforming import` returns: 
"cloudflare_healthcheck" is not yet supported for state import

### Steps to reproduce

1.`cf-terraforming generate --resource-type "cloudflare_healthcheck" --zone "xxxxxx" > zone.tf`
2. `echo $?`  ---> returns "0"
3. `cf-terraforming import --resource-type "cloudflare_healthcheck" --zone "xxxxxx"`
4. `echo $?`  ---> returns "08123"

**Comment by lushndm** [comment]
+1
