### ISSUE TITLE
FATA[0003] failed to detect provider installation

### ISSUE THREAD

**Issue by mvasilenko** [cloudflare/cf-terraforming#328]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.5.0

### Expected outcome

generate terraform stanzas

### Actual outcome

DEBU[0000] initializing cloudflare-go with API Token     account_Id=12345 zone_id=67890
DEBU[0000] configuring Cloudflare API with account       account_id=12345
DEBU[0004] initialising Terraform in .
DEBU[0007] reading Terraform schema for Cloudflare provider
FATA[0010] failed to detect provider installation

### Steps to reproduce

```
terraform init
cf-terraforming generate --token $CLOUDFLARE_API_TOKEN \
    -z 67890 --account 12345 --resource-type cloudflare_record -v
```

at the same time `cf-terraforming import` works just fine
any suggestions on how to troubleshoot it?

provider versions:

```
.terraform/providers/registry.terraform.io/hashicorp/aws/3.68.0/darwin_amd64
281376448 Dec  3 11:28 terraform-provider-aws_v3.68.0_x5

.terraform/providers/registry.terraform.io/terraform-providers/cloudflare/3.4.0/darwin_amd64
23759632 Dec  3 11:28 terraform-provider-cloudflare_v3.4.0
```

### References

https://github.com/cloudflare/cf-terraforming/issues/310

**Comment by jacobbednarz** [comment]
please see the issue you've linked to. this tool requires that Terraform is already installed and correctly initialised where you're attempting to use cf-terraforming. 

if you're stuck, you can check out the release blog article which has a 0 to up and running tutorial - https://blog.cloudflare.com/cloudflares-partnership-with-hashicorp-and-bootstrapping-terraform-with-cf-terraforming/

**Comment by mvasilenko** [comment]
@jacobbednarz thanks for the quick response, 
I've run `terraform init` previously as required in README, `terraform` is installed and working in that particular directory, `terraform providers schema -json` producing huge JSON output

so I'm a bit stuck how to troubleshoot it further
