### ISSUE TITLE
Failed to read provider schema when trying to generate records.

### ISSUE THREAD

**Issue by bourbonfgiles** [cloudflare/cf-terraforming#337]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming generate --resource-type "cloudflare_record" -z "f811b7bc68e60d762e0e0428eabded8f" -k $CLOUDFLARE_API_KEY -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL --verbose > zego_dot_fr_records.tf DEBU[0000] initializing cloudflare-go                    account_id=667738ac3be244af9cb3db2849cc1b04 email="“benjamin.giles@zego.com”" zone_id=f811b7bc68e60d762e0e0428eabded8f DEBU[0000] configuring Cloudflare API with account       account_id=667738ac3be244af9cb3db2849cc1b04 DEBU[0003] initialising Terraform in . DEBU[0008] reading Terraform schema for Cloudflare provider FATA[0011] failed to read provider schemaunsupported provider schema data format version: expected ["0.1" "0.2"], got "1.0"

### Expected outcome

I expected a file containing the records in the above mentioned zone. 

I have a .sh script I dot slash to export the variables required. This has worked for me previously with no problems at all.

### Actual outcome

I'm also failing to import records using cf-terraforming

`cf-terraforming import --resource-type "cloudflare_record" -z "f811b7bc68e60d762e0e0428eabded8f" -k $CLOUDFLARE_API_KEY -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL
FATA[0000] HTTP status 400: Authentication error (10000)`

Now to be clear, the authentication key seems to work just fine for Terraform plans and applies. 

### Steps to reproduce

This might be a local issue, the only change is I've moved from my old MacBook to a new one. Both are M1 based, and cf-terraforming was installed via brew install on both machines.

**Comment by gray1117** [comment]
I've noticed this error has shown up in cf-tf v0.4.0; wasn't present until last week.  v0.5.0 and v0.6.0 work

DEBU[0008] reading Terraform schema for Cloudflare provider FATA[0011] failed to read provider schemaunsupported provider schema data format version: expected ["0.1" "0.2"], got "1.0"

**Comment by bourbonfgiles** [comment]
Upgrading works!
