### ISSUE TITLE
@jacobbednarz Supported Resources list is not accurate

### ISSUE THREAD

**Issue by antigenius0910** [cloudflare/cf-terraforming#338]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.5.0

### Expected outcome

As README state it should have 32 resources available for "both generate and import"

![Screen Shot 2021-12-16 at 11 51 46 AM](https://user-images.githubusercontent.com/5915590/146423402-4c41cb87-1ca4-4564-99f6-2d6b1affdfd3.png)

in fact, there is only 22 of them support import as you can see from the code
https://github.com/cloudflare/cf-terraforming/blob/master/internal/app/cf-terraforming/cmd/import.go#L18-L40

Need to add another column which separate ```generate``` and ```import``` code status

### Actual outcome

10 resources from your list is not yet supported for state import

### Steps to reproduce

```
cf-terraforming import \  
--zone $CLOUDFLARE_ZONE_ID --resource-type $RESOURCE
```

### References

![Screen Shot 2021-12-16 at 11 55 39 AM](https://user-images.githubusercontent.com/5915590/146423819-8566a573-b0bf-4dc5-b6fd-c1e997b058c2.png)

https://github.com/cloudflare/cf-terraforming/pull/236

 @jacobbednarz

**Comment by garrettgalow** [comment]
should be fixed by what was merged today
