### ISSUE TITLE
API key problem

### ISSUE THREAD

**Issue by bourbonfgiles** [cloudflare/cf-terraforming#342]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.6.0

### Expected outcome

Generate terraform resources. 

Using an API key that successfully works for a terraform plan or apply, I get an authentication error when using cf-terraforming to import.

`cf-terraforming import --resource-type "cloudflare_record" -z ""zoneid" -k $CLOUDFLARE_API_KEY -a $CLOUDFLARE_ACCOUNT_ID -e $CLOUDFLARE_EMAIL`

Using the above command where zoneid is a real zone, and the environment variables are exported using a shell script.

### Actual outcome

FATA[0000] HTTP status 400: Authentication error (10000)

### Steps to reproduce

I've double checked I'm using the same key for plan, applies and cf-terraforming. 

What else can I do to troubleshoot this?

**Comment by jacobbednarz** [comment]
you can use a MITM proxy to debug what the HTTP request is doing along with the —debug flag in cf-terraforming to confirm it is authenticated correctly.
