### ISSUE TITLE
-z --zone switch not working

### ISSUE THREAD

**Issue by aldric** [cloudflare/cf-terraforming#345]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

FATA[8146] configuration is invalid

### Expected outcome

I would have liked that only my zone config get output. I have tried different switch location in my command but it just get all my domains within my account. No error when I run the command but just crash at the end.
The problem is that I manage more than 14K+ domains on CF and I wanted to generate files per domains with all the related information I need for each of them.
Right now I have tried  the switch (-z --zone) in different formats  (with and without ") and different location (beginning or end of the command), but it is still the same, no error but trying to get all my domains,
It was ok to retrieve my cloudflare_records and now I would like to get all my zones, workers, firewall config but I can't.
Thanks,

### Actual outcome

Do not filter as per zone switch provided

### Steps to reproduce

cf-terraforming --zone any_zone_id -c ./.cf-terraforming.yaml   generate --resource-type cloudflare_record > records_any_zone_id.tf

**Comment by jacobbednarz** [comment]
the zone flag works; the error message you are getting is related to Terraform itself not being properly initialised. it needs to be a working install before cf-terraforming can operate on it. I’d suggest starting with that and working backwards to cf-terraforming and exporting the resources.
