### ISSUE TITLE
importing dns records to state file

### ISSUE THREAD

**Issue by pastephens** [cloudflare/cf-terraforming#35]
I downloaded my DNS records with cf-terraforming, and now want to push/apply them to my existing state bucket in S3.  Since the record(s) already exists, terraform errors with an HTTP 400.  I'm not sure where this should go - possibly to the API maintainers? To the Terraform provider maintainers? To hashicorp? Ideally, an existing resource would issue a 200 and just move on, maybe?

---
> $ tf apply -var-file=local.tfvars
...

`An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + cloudflare_record.<my_string>
      id:          <computed>
      created_on:  <computed>
      domain:      "redacted.com"
      hostname:    <computed>
      metadata.%:  <computed>
      modified_on: <computed>
      name:        "redacted.com"
      proxiable:   <computed>
      proxied:     "true"
      ttl:         "1"
      type:        "A"
      value:       "x.x.x.x"
      zone_id:     <computed>

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_record.<my_stirng>: Creating...
  created_on:  "" => "<computed>"
  domain:      "" => "redacted.com"
  hostname:    "" => "<computed>"
  metadata.%:  "" => "<computed>"
  modified_on: "" => "<computed>"
  name:        "" => "redacted.com"
  proxiable:   "" => "<computed>"
  proxied:     "" => "true"
  ttl:         "" => "1"
  type:        "" => "A"
  value:       "" => "x.x.x.x"
  zone_id:     "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* cloudflare_record.<my_string>: 1 error(s) occurred:

* cloudflare_record.redacted: Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":81057,\"message\":\"The record already exists.\"}],\"messages\":[],\"result\":null}"`

**Comment by pastephens** [comment]
This was user input error. I'm going to leave a little bread crumb here for anyone else having trouble importing records into state:

cf-terraforming produces a file with a number of resource definitions, like this one:

```
resource "cloudflare_record" "A_asite_someu_edu_ca90a77464cc678a2d9ae18ba3ee4f75" {
  domain = "someu.edu"
  name    = "asite.someu.edu"
  type    = "A"
  ttl     = "1"
  proxied = "true"
  value = "x.x.x.x"
}
```

The correct corresponding terraform command is like this:

`terraform import cloudflare_record.A_asite_someu_edu_ca90a77464cc678a2d9ae18ba3ee4f75 someu.edu/ca90a77464cc678a2d9ae18ba3ee4f75`

**Comment by zackproser** [comment]
Thanks for the update and for leaving the bread crumb for posterity!
