### ISSUE TITLE
Unable to install with brew due to SHA256 mismatch error

### ISSUE THREAD

**Issue by pastephens** [cloudflare/cf-terraforming#352]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

n/a

### Expected outcome

cf-terraforming installed

### Actual outcome

╰─$ brew install --cask cloudflare/cloudflare/cf-terraforming
==> Downloading https://github.com/cloudflare/cf-terraforming/releases/download/v0.6.0/cf-terraforming_0.6.0_darwin_amd64.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/160878303/dc8827a0-0964-490e-90a7-bd0423d
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: cad76567c1f0ba0266d950dbff3b42bbf423025eb73f967c7092e2ab71bc69be
  Actual: 2ca219c1ab865c52a6cae7db059aac7b94130ad903f6020b1f741b438daa14f8
    File: /Users/phil/Library/Caches/Homebrew/downloads/807dd579c88e7be25263b8c4e9db2e1ef195d1b7018786d2bd98c624a8b1f9f8--cf-terraforming_0.6.0_darwin_amd64.tar.gz
To retry an incomplete download, remove the file above.

### Steps to reproduce

$ brew tap cloudflare/cloudflare
$ brew install --cask cloudflare/cloudflare/cf-terraforming

**Comment by darkorb** [comment]
Looks like it's reported in the Cask repo - https://github.com/cloudflare/homebrew-cloudflare/issues/39

**Comment by evanhfox** [comment]
A workaround until that PR is reviewed by maintainers is to edit the formula locally (it'll be cached on your system after a brew update). 

Workaround:
1. Edit the cf-terraforming formula via `brew edit cf-terraforming`
2. Edit the version to 0.6.3 and add the new accompanying SHA256 checksums. The full edited formula will look as follows:

```
<ibrary/Taps/cloudflare/homebrew-cloudflare/Casks/cf-terraforming.rb" 17L, 807B
cask "cf-terraforming" do
  name "cf-terraforming"
  appcast "https://github.com/cloudflare/cf-terraforming/releases.atom"
  homepage "https://github.com/cloudflare/cf-terraforming"
  desc "cf-terraforming is a command line utility to facilitate terraforming your existing Cloudflare resources"
  version "0.6.3"

  if Hardware::CPU.intel?
    url "https://github.com/cloudflare/cf-terraforming/releases/download/v#{version}/cf-terraforming_#{version}_darwin_amd64.tar.gz"
    sha256 "cad76567c1f0ba0266d950dbff3b42bbf423025eb73f967c7092e2ab71bc69be"
  else
    url "https://github.com/cloudflare/cf-terraforming/releases/download/v#{version}/cf-terraforming_#{version}_darwin_arm64.tar.gz"
    sha256 "b45406cd187b4e848fe050ede767e3705c4ddd4d8f5c051a727fd81eccdfc30a"
  end

3. do a `brew install cf-terraforming`. You should be able to successfully install 0.6.3 after the above edits.

  binary "cf-terraforming"
end
```

**Comment by mikegreen** [comment]
Closing this so others don't see it as an active issue, nor mentioned in the readme, is pretty annoying. If brew isn't working, can we note that on the readme and keep the issue open until its resolved? Having everyone who tries to use brew to install spend 10 more minutes researching and fixing the SHA is silly - if I knew that I'd just have built it on my own.

**Comment by evanhfox** [comment]
@mikegreen A merge happened this morning that has resolved the issue.
