### ISSUE TITLE
cloudlare_zone_settings_override is not yet supported, yet listed as supported in docs

### ISSUE THREAD

**Issue by pastephens** [cloudflare/cf-terraforming#353]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.6.3

### Expected outcome

╰─$ cf-terraforming generate --resource-type "cloudlare_zone_settings_override" --account $CLOUDFLARE_ACCOUNT_ID

< insert magically generated code!

### Actual outcome

╰─$ cf-terraforming generate --resource-type "cloudlare_zone_settings_override" --account $CLOUDFLARE_ACCOUNT_ID
"cloudlare_zone_settings_override" is not yet supported for automatic generation⏎

### Steps to reproduce

export CLOUDFLARE_ACCOUNT_ID and TOKEN
Install latest cf-terraforming version
terraform init 
 cf-terraforming generate --resource-type "cloudlare_zone_settings_override" --account $CLOUDFLARE_ACCOUNT_ID

### References

None

**Comment by jacobbednarz** [comment]
looks like you’ve got a typo as this is definitely supported and asserted against in tests. 

`cloudlare_zone_settings_override` -> `cloudflare_zone_settings_override`
