### ISSUE TITLE
generate all resource for one site

### ISSUE THREAD

**Issue by thomaslui1980** [cloudflare/cf-terraforming#363]
### Current `cf-terraforming` version

v0.6.3-dev+b63c1cb96926

### Description

for example, one site has been created in cloudflare and setup waf rules. In this case, if we want to generate all resource related to this site, is there any way to do it?

### Use cases

Get all resource info for one site.

### Potential `cf-terraforming` usage

./cf-terraforming genearte --account '210e085ebaad540bef551adff54f3aef' --zoneid "zoneid"

### References

no

**Comment by jacobbednarz** [comment]
see #194 why this isn’t something we’ve added (and no plans to at the moment).
