### ISSUE TITLE
Generated `cloudflare_zone_settings_override` use deprecated arguments

### ISSUE THREAD

**Issue by xakraz** [cloudflare/cf-terraforming#365]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.6.3

### Expected outcome

I have run 

```
cf-terraforming generate \
  --account ${CLOUDFLARE_ACCOUNT_ID} \
  --zone ${CLOUDFLARE_ZONE_ID} \
  --token ${CLOUDFLARE_API_TOKEN} \
  --resource-type cloudflare_zone_settings_override \
  --terraform-install-path /src/code/ \
  --verbose
```

I am expecting to get a functional Terraform resource.

### Actual outcome

```
$ terraform plan

...

╷
│ Warning: Argument is deprecated
│
│   with cloudflare_zone_settings_override.ZONE_NAME,
│   on zone.tf line 59, in resource "cloudflare_zone_settings_override" "ZONE_NAME":
│   59:     tls_1_2_only                = "off"
│
│ tls_1_2_only has been deprecated in favour of using `min_tls_version =
│ "1.2"` instead.
│
│ (and one more similar warning elsewhere)
```

### Steps to reproduce

1. Download the specified version of `cf-terraforming`
2. Set the expected variables (AccountId, ZoneId, API Token)
3. Run the mentioned command `cf-terraforming generate --resource-type cloudflare_zone_settings_override`
4. Run `terraform plan` with the generated resource

### References

While generating the resource, `cf-terraforming` has updated the terraform provider to its latest version

```
.terraform.lock.hcl
-------------------
provider "registry.terraform.io/cloudflare/cloudflare" {
  version     = "3.9.1"
  constraints = "~> 3.0"
```

but still generates resources with deprecated arguments...

**Comment by jacobbednarz** [comment]
this is expected behaviour as some configurations have not yet moved over and will still be sending the attributes. if you are not using it, please just remove it from your configuration file.

**Comment by xakraz** [comment]
Hi @jacobbednarz ,
Thanks for your reply.

What about the other way around?

I have found some properties in the [Terraform resources](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override) that are not listed by the API:
```
curl -X GET "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/settings"
```

```
binary_ast
universal_ssl
h2_prioritization
image_resizing
```
