### ISSUE TITLE
Provide generate option to include resourceId needed for subsequent Terraform import

### ISSUE THREAD

**Issue by rbgigo** [cloudflare/cf-terraforming#383]
### Current `cf-terraforming` version

0.6.0

### Description

_Generate_ command shall provide option that will include the actual resourceId of the object as "comment" data field in the stanza allowing to subsequently generate terraform import commands which require the zoneId as well as the  resourceId as parameter. 

### Use cases

When Cloudflare objects have been created by means other than Terraform it is required to work up a Terraform state file reflecting the real world state, which is only possible if the object's resourceId is at hand. As long this information is not available is required to query the resourceId with an additional Cloudflare API call. It is clear that the resourceId is computed at object creation time therefore the stanza should provide this info as comment.

Alternatively the resourceId could also be derived from the resource name which is not as elegant as having a data field

### Potential `cf-terraforming` usage

resource "cloudflare_record" "terraform_managed_resource_09e894361db4038896f2dba2a2f9c789" {
  name    = "abcdef"
  proxied = true
  ttl     = 1
  type    = "CNAME"
  value   = "abcdef.azure-api.net"
  zone_id = "272f7e575817d405fff08d39e931097d"
  **_resource_id_ = "09e894361db4038896f2dba2a2f9c789"**
}

**Comment by jacobbednarz** [comment]
the `generate` command doesn't actually need the ID; instead the `import` command is what takes care of this and outputs the correctly formatted `import` command to add the resources into your state file.

see the [announcement blog](https://blog.cloudflare.com/cloudflares-partnership-with-hashicorp-and-bootstrapping-terraform-with-cf-terraforming/) for some details on how these work together.

**Comment by rbgigo** [comment]
Hi Jacob

That is clear that the generate command does not require the resourceId but if I want to generate import commands out of the generate output I need this information, simple as that
