### ISSUE TITLE
Provide generate option to include child 

### ISSUE THREAD

**Issue by rbgigo** [cloudflare/cf-terraforming#384]
### Current `cf-terraforming` version

0.6.0

### Description

Generate command should accept option allowing to generate Terraform stanzas for the base object plus all its dependent objects

### Use cases

When migrating certain objects from one site to another often all related objects are required to be copied over to the new target, e.g. dns_record plus linked access app, access policy, page rule and so on.

### Potential `cf-terraforming` usage

cf-terraforming generate  --zone $CLOUDFLARE_ZONE_ID  --resource-type "cloudflare_record" --include-child-objects

**Comment by jacobbednarz** [comment]
thanks for the suggestion however there isn't any plans to include this functionality largely because we don't have these relationships mapped anywhere externally. it is all business logic and not something we'd expose externally in the current state.

**Comment by rbgigo** [comment]
One can argue whether this is business logic. Fact is that when assigning an app policy to a certain URL is create a dependency, so the DNS being the root element is linked and makes the access app and policy a child object out of it. 

Due to Cloudflare lacking some export/import function, the users are forced to implement that on their own which is not a nice user experience
