### ISSUE TITLE
Some resources are read-only for free accounts

### ISSUE THREAD

**Issue by angristan** [cloudflare/cf-terraforming#40]
Hello,

I backported `cloudflare_zone_settings_override` using cf-terraforming.

When applying, I get this error:

```
Error: Error applying plan:

1 error(s) occurred:

* cloudflare_zone_settings_override.settings: 1 error(s) occurred:

* cloudflare_zone_settings_override.settings: invalid zone setting "sort_query_string_for_cache" (value: off) found - cannot be set as it is read only
```

So I suppose cf-terraforming should no retrieve "sort_query_string_for_cache", since it cannot be modified by Terraform.

**Comment by zackproser** [comment]
Thanks for the report. We will look into this.

**Comment by angristan** [comment]
Same with webp:

```
* cloudflare_zone_settings_override.zone_settings: invalid zone setting "webp" (value: off) found - cannot be set as it is read only
```

**Comment by angristan** [comment]
That's because `sort_query_string_for_cache` is for the enterprise plan and `webp` is for the pro plan.

Maybe cf-terraforming could detect the plan of the zone and include this settings only if they are available?

**Comment by ricardbejarano** [comment]
This is still an issue, as far as I can tell.
