### ISSUE TITLE
macOS: FATAL on cf-terraforming generate

### ISSUE THREAD

**Issue by vanmash** [cloudflare/cf-terraforming#400]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.7.3

### Expected outcome

`generate` output

### Actual outcome

DEBU[0000] initializing cloudflare-go with API Token     account_Id= zone_id=
DEBU[0003] initializing Terraform in .                  
FATA[0004] exit status 1

Error: Failed to decode current backend config

The backend configuration created by the most recent run of "terraform init"
could not be decoded: unsupported attribute "use_microsoft_graph". The
configuration may have been initialized by an earlier version that used an
incompatible configuration structure. Run "terraform init -reconfigure" to
force re-initialization of the backend.

### Steps to reproduce

1. `terraform init`
2. `cf-terraforming generate --resource-type "cloudflare_record" -v`

### References

terraform version
Terraform v1.1.8
on darwin_arm64

cloudflare 3.12.2 

azurerm 3.20

**Comment by jacobbednarz** [comment]
this looks to be an issue outside of cf-terraforming as the error mentions a non-Cloudflare resource. i'd suggest starting there with `terraform` commands to work out what is breaking.
