### ISSUE TITLE
Support for cloudflare_waf resources

### ISSUE THREAD

**Issue by NicklasWallgren** [cloudflare/cf-terraforming#403]
### Current `cf-terraforming` version

0.7.3

### Description

Provide support for cloudflare_waf resources.

### Use cases

To be able to import cloudflare_waf resources.

### Potential `cf-terraforming` usage

cf-terraforming generate --resource-type "cloudflare_waf_*"
cf-terraforming import --resource-type "cloudflare_waf_*"

### References

https://github.com/cloudflare/cf-terraforming/pull/350

**Comment by garrettgalow** [comment]
Due to the deprecation of the legacy waf we won't be making any updates to the legacy waf resources. Please use `cloudflare_ruleset` going forward
