### ISSUE TITLE
cf-terraforming error: unexpected Content-Type

### ISSUE THREAD

**Issue by ThomasAusweger** [cloudflare/cf-terraforming#406]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.7.3

### Expected outcome

Connect to cloudflare and generate export for the zone

### Actual outcome

$cf-terraforming version
cf-terraforming v0.7.3

$cf-terraforming -v --resource-type "cloudflare_firewall_rule" --email $EMAIL --key $API_KEY --zone $ZONE
DEBU[0000] initializing cloudflare-go                    account_id= email=****** zone_id=*******
FATA[0000] error installing Terraform: unexpected Content-Type: "application/vnd+hashicorp.releases-api.v0+json"

### Steps to reproduce

Try to connect to cloudflare

**Comment by ThomasAusweger** [comment]
Sorry just found the duplicate https://github.com/cloudflare/cf-terraforming/issues/405

**Comment by jafowler** [comment]
closing in favor of #405
