### ISSUE TITLE
error installing Terraform: unexpected Content-Type: "application/vnd+hashicorp.releases-api.v0+json"

### ISSUE THREAD

**Issue by StickeyTape** [cloudflare/cf-terraforming#409]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.7.3

### Expected outcome

running  cf-terraforming generate should generate output and not produce error.

cf-terraforming generate --resource-type cloudflare_load_balancer --zone $cloudflare_zone_id  --email ${cloudflare_email}   --key ${cloudflare_api_key}

Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.14.0

expected outcome should be terraform style output for resource definitions

### Actual outcome

FATA[0000] error installing Terraform: unexpected Content-Type: "application/vnd+hashicorp.releases-api.v0+json"

### Steps to reproduce

1. Create main.tf and specify resource provider
 `terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }

}

provider "cloudflare" {
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}`

2. run cf-terraform generate with the require flags
`cf-terraforming generate --resource-type cloudflare_load_balancer --zone $cloudflare_zone_id  --email ${cloudflare_email}   --key ${cloudflare_api_key}`

3. have tested with all resource-types

**Comment by jafowler** [comment]
This should be fixed in v0.7.4 (just released today)

**Comment by troymjones** [comment]
@jafowler - when do you expect homebrew to be updated for macos?

**Comment by troymjones** [comment]
I see it has just now been updated

**Comment by jafowler** [comment]
Yeah, i was working on updating it and @manatarms sniped it 😅

**Comment by aauVadim** [comment]
@jafowler Thank you guys for quick fix! It works for me now.

**Comment by StickeyTape** [comment]
Awesome Work .. mine working too.
