### ISSUE TITLE
cloudflare_page_rule import does not have zone_id in generate

### ISSUE THREAD

**Issue by StickeyTape** [cloudflare/cf-terraforming#411]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.7.4

### Expected outcome

Output should include the **zone_id** 

resource "cloudflare_page_rule" "terraform_managed_resource_YYYYYYYYYYYY" {
  **zone_id = YYYYYYYYYYYY** 
  priority = 1
  status   = "active"
  target   = "domain.com/*"
  actions {
    forwarding_url {
      status_code = 301
      url         = "https://www.domain.com"
    }
  }
}

### Actual outcome

Due to the fact that zone_id is not in the output, the terraform plan fails.

resource "cloudflare_page_rule" "terraform_managed_resource_YYYYYYYYYYYY" {
  priority = 1
  status   = "active"
  target   = "domain.com/*"
  actions {
    forwarding_url {
      status_code = 301
      url         = "https://www.domain.com"
    }
  }
}

Terraform plan output:
│ Error: Missing required argument
│
│   on main.tf line 1, in resource "cloudflare_page_rule" "terraform_managed_resource_YYYYYYYYYYYY":
│    1: resource "cloudflare_page_rule" "terraform_managed_resource_YYYYYYYYYYYY" {
│
│ The argument "zone_id" is required, but no definition was found.

### Steps to reproduce

1. Run : ./cf-terraforming -e me@mail.com -k KKKK -a AAAA -z YYYYYYYYYYYY generate --resource-type cloudflare_page_rule > main.tf
2. Run : terraform plan -var cloudflare_email=me@mail.com -var cloudflare_api_key=KKKK -var cloudflare_account_id=AAAA

**Comment by jacobbednarz** [comment]
can you try removing the account identifier in your CLI arguments (page rules don't exist at an account level)? `zone_id` is appearing for me when it isn't present. note: there is a warning about `zone` and `account` flag being deprecated due to undefined behaviour like this.

**Comment by StickeyTape** [comment]
Interestingly this was a working configuration that stopped, and this morning it appears to be working again as is.
A complete re-import of the state file was done (not using cf-terraforming import). Unfortunately I didnt back up the previous state file to compare to see if maybe there was some corruption in it.

For now its working - will have to see if it comes back again..
