### ISSUE TITLE
Add generate support for Cloudflare Teams/Zero Trust resources

### ISSUE THREAD

**Issue by rukia-a** [cloudflare/cf-terraforming#424]
### Current `cf-terraforming` version

v0.7.4

### Description

This issue is requesting configuration generation support for Cloudflare Teams/Zero Trust resource to help pre-existing accounts migrate into terraform.

### Use cases

These resources would allow for easier migration to terraform for future management, and would provide visibility into configurations set in Cloudflare Teams/Zero Trust for those who initially set it up outside of terraform. 

Additionally, because the resource's product is something that impacts end-user network traffic, this configuration would need to be completely replicated in order to move to management with terraform with minimal disruption for those with it deployed.

### Potential `cf-terraforming` usage

`cf-terraforming generate --token $CLOUDFLARE_API_TOKEN -a $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_teams_account"`

`cf-terraforming generate --token $CLOUDFLARE_API_TOKEN -a $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_teams_list"`

`cf-terraforming generate --token $CLOUDFLARE_API_TOKEN -a $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_teams_location"`

`cf-terraforming generate --token $CLOUDFLARE_API_TOKEN -a $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_teams_proxy_endpoint"`

`cf-terraforming generate --token $CLOUDFLARE_API_TOKEN -a $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_teams_rule"`

**Comment by vDMG** [comment]
Hello, having `cloudflare_teams_rule` will be awesome due to the fact that the actual implementation is hard to understand and maintain on terraform using cloudflare provider

**Comment by devinbfergy** [comment]
Adding support for everything mentioned but **cloudflare_teams_account** in this PR https://github.com/cloudflare/cf-terraforming/pull/669
