### ISSUE TITLE
Add support for cloudflare_list

### ISSUE THREAD

**Issue by pastephens** [cloudflare/cf-terraforming#444]
### Current `cf-terraforming` version

cf-terraforming v0.8.0

### Description

[cloudflare_list](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/list) encompasses ip_lists and redirect_lists, allowing the management of CF Bulk Redirects. You already support ip_lists and this is, I think, a subclass of a generic CF List.

### Use cases

CF Bulk Redirects was introduced in Beta. We initially transformed our redirect data set into csv format and uploaded using the provided gui functionality. Those resources, however, are not currently captured as Infrastructure-as-Code. We want to manage them using Terraform by first importing them using cf-terraforming.

## Example usage

```bash
$ cf-terraforming generate \
  --zone $CLOUDFLARE_ZONE_ID \
  --resource-type "cloudflare_list"
```

will contact the Cloudflare API on your behalf and result in a valid Terraform
configuration representing the **resource** you requested:

```hcl
resource "cloudflare_list" "terraform_managed_resource" {
  name = "example.com"
  list_name = "example"
  list_type = "redirect_list"  # could be ip_list
  zone_id = "0da42c8d2132a9ddaf714f9e7c920711"
}
```

**Comment by Arnall** [comment]
Note : `cloudflare_ip_list` is marked as deprecated in favor of `cloudflare_list`.

https://github.com/cloudflare/terraform-provider-cloudflare/blob/5c425613d6aa142eb306d3b7017eb4ad9e2e0f8e/internal/provider/resource_cloudflare_ip_list.go#L15-L16

https://github.com/cloudflare/terraform-provider-cloudflare/blob/5c425613d6aa142eb306d3b7017eb4ad9e2e0f8e/internal/provider/resource_cloudflare_ip_list.go#L28

**Comment by Arnall** [comment]
Hello,

the Cloudflare provider does not support `cloudflare_ip_list` anymore !

regards.

**Comment by steadfasterX** [comment]
- `cloudflare_ip_list` is not working anymore (_"cloudflare_ip_list" is not yet supported for automatic generation_)
- `cloudflare_list` is not integrated
- and it seems the whole code related to that topic has been removed
- it still shows up as _supported_ in the [README](https://github.com/cloudflare/cf-terraforming#supported-resources)

would really like to see  `cloudflare_list`  in the future, previous PR reg `cloudflare_ip_list` is here: https://github.com/cloudflare/cf-terraforming/pull/462

related terraform link: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/list

**Comment by dvasdekis** [comment]
Cmon guys, can we please have supoprt for "cloudflare_list"? Looks like the work was mostly done
