### ISSUE TITLE
cloudflare_access_policy | cf-terraforming | support availability

### ISSUE THREAD

**Issue by udaydaayam** [cloudflare/cf-terraforming#451]
### Current `cf-terraforming` version

cloudflare_access_policy | cf-terraforming | support availability

### Description

Hi Team,

May I know when is the tentative date for availbility of cf-terraforming for cloudflare_access_policy resources generate/import.

Thanks,
Uday

### Use cases

Hi Team,

May I know when is the tentative date for availbility of cf-terraforming for cloudflare_access_policy resources generate/import.

Thanks,
Uday

### Potential `cf-terraforming` usage

Hi Team,

May I know when is the tentative date for availbility of cf-terraforming for cloudflare_access_policy resources generate/import.

Thanks,
Uday

### References

Hi Team,

May I know when is the tentative date for availbility of cf-terraforming for cloudflare_access_policy resources generate/import.

Thanks,
Uday

**Comment by jacobbednarz** [comment]
there is no current ETA.
