### ISSUE TITLE
Cache keys are not escaped

### ISSUE THREAD

**Issue by mutt13y** [cloudflare/cf-terraforming#46]
resource "cloudflare_page_rule" "REDACTED"
      zone = "REDACTED"
      target = "REDACTED"
      priority = 9

      actions = {
        cache_level = "cache_everything"
        edge_cache_ttl = 14400

        cache_key = "${header:origin}::${scheme}://${host_header}${uri_iqs}"
      }
    }

This cache key is dumped literally from the CF rule however $ { and : are special characters to terraform and so this string needs to be quoted

_terraform validate_

    Error: Error loading ./main.tf: Error reading config for cloudflare_page_rule[REDACTED]: parse error at 1:9: expected "}" but found ":"

**Comment by deppy** [comment]
This issue also extends to anything where the value had quotes... I had something show up as:

```
value = ""Hello world""
```

**Comment by syed-awais-ali** [comment]
Have you tried escaping characters because `${}` this will try and evaluate this as an interpolation function. But you want to use this value literally so you should change this to 
```
cache_key = "$${header:origin}::$${scheme}://$${host_header}$${uri_iqs}"
```
and see whether it resolves your issue. Most likely cache_key would itself raise some error as I was unable to find it in Terraform [docs](https://www.terraform.io/docs/providers/cloudflare/r/page_rule.html).

**Comment by mutt13y** [comment]
hi @syed-awais-ali ,
This is a utility that is supposed to generate the terraform code from the existing configuration. As such it should come quoted already.

You are correct in that I could edit the output and add the extra $

**Comment by syed-awais-ali** [comment]
Hi @mutt13y,
I need to know about the usage of cache-key in `action` block, because as there is nothing as such in Terraform docs.

I hope I have made my self more clear, please let me know if I am still not clear enough. Thanks

**Comment by mutt13y** [comment]
I have posted a sample output of running cf-terraforming against our CF configuration.
The output is invalid terraform code

**Comment by Yanisky** [comment]
It's possible to test escaping problems with a simple "TXT" record.

If in Cloudflare's configuration there is a TXT DNS record with a double quotation mark in its value (e.g testing ")  cf-terraforming will output this to the configuration file without escaping thus becoming an incorrect terraform value.

In Cloudflare:
```
TXT    test_escape    test escape "
```
if you import the above DNS record it will result in a .tf file with the following:
```
... {
    ...
    value = "test escape ""
}
```
Notice the double quotations marks at the end.
