### ISSUE TITLE
FATA[0005] terraform 1.0.6 not supported by configuration (>= 1.1.7 required) 

### ISSUE THREAD

**Issue by bensig** [cloudflare/cf-terraforming#467]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.8.4

### Expected outcome

Running `cf-terraforming generate` should connect to my cf and generate records. I have terraform 1.2.9 installed on OS X via brew. Also installed cf-terraforming from brew using instructions on the readme in this repo.

### Actual outcome

Error `FATA[0005] terraform 1.0.6 not supported by configuration (>= 1.1.7 required) `

### Steps to reproduce

`cf-terraforming generate`

**Comment by jacobbednarz** [comment]
this isn't a restriction in the tool but your configuration. in the directory you are attempting to run this, there will be a version constraint and the version of the binary the tool detects is older than that. you'll need to rectify that in order to continue.

**Comment by bensig** [comment]
Thanks. Why does it detect a different version?

**Comment by jacobbednarz** [comment]
cf-terraforming detects the first binary on the path and uses it. you'll need to debug why there is a conflict or remove the other versions.
