### ISSUE TITLE
Complete/Recursive Import of all resources per zone

### ISSUE THREAD

**Issue by emilwester-optimizely** [cloudflare/cf-terraforming#473]
### Current `cf-terraforming` version

0.8.4

### Description

It would be _VERY_ nice and convenient if you could import all resource_types in a zone in one command.

### Use cases

It's very tedious and time-consuming to run multiple generates & imports over large zones that have a lot of settings. this feature would lower the bar for adoption of the tool

### Potential `cf-terraforming` usage

cf-terraforming generate -e 'USER' -k 'KEY' -z 'ZONE' --resource-type 'all' 

OR 

cf-terraforming generate -e 'USER' -k 'KEY' -z 'ZONE' --resource-type-recursive

### References

have a look at https://github.com/azure/aztfy where you can import whole resource groups from azure in one go.

**Comment by jacobbednarz** [comment]
see https://github.com/cloudflare/cf-terraforming/issues/194 why this isn’t something we’ve added (and no plans to at the moment).

**Comment by Kampe** [comment]
WILDLY useful if this existed.

**Comment by noahkiss** [comment]
This should work for anyone using bash or zsh. Can probably be easily translated to PS if necessary.

run it in your terraform dir which is already initialized. if unfamiliar, I'll post some extra code at the bottom.

it'll create files named `_(resource)_(domain.tld).tf` which may result in a lot of files, but you can either modify the script or manually handle that elsewhere.

macOS users may need to "brew install jq" if you haven't already.

<details>
<summary>Setup</summary>

```bash
# CLOUDFLARE_TF_TOKEN="" # or export to environment

declare -A zone

# Get all zones
api_endpoint="https://api.cloudflare.com/client/v4/zones"

response=$(curl -s -X GET "$api_endpoint" \
    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    -H "Content-Type: application/json")

echo "$response" \
| jq -r '.result[] | "\(.name)=\(.id)"' \
| while IFS="=" read -r domain id; do
    zone[$domain]="$id"
done

### paid plans only
# cloudflare_api_shield
# cloudflare_argo
# cloudflare_custom_hostname
# cloudflare_custom_ssl
# cloudflare_spectrum_application
###

zone_scoped_resources=(
cloudflare_authenticated_origin_pulls
cloudflare_authenticated_origin_pulls_certificate
cloudflare_bot_management
cloudflare_certificate_pack
cloudflare_filter
cloudflare_firewall_rule
cloudflare_healthcheck
cloudflare_load_balancer
cloudflare_logpull_retention
cloudflare_logpush_job
cloudflare_logpush_ownership_challenge
cloudflare_origin_ca_certificate
cloudflare_page_rule
cloudflare_rate_limit
cloudflare_record
cloudflare_tiered_cache
cloudflare_url_normalization_settings
cloudflare_waf_group
cloudflare_waf_override
cloudflare_waf_package
cloudflare_waf_rule
cloudflare_waiting_room
cloudflare_worker_route
cloudflare_zone_dnssec
cloudflare_zone_lockdown
cloudflare_zone_settings_override
)
```

</details>

<details>
<summary>Bash only</summary>

```bash
for resource in "${zone_scoped_resources[@]}"; do
    for name in "${!zone[@]}"; do
        id=${zone[$name]}

        temp_file=$(mktemp)

        cf-terraforming generate \
            --resource-type "$resource" \
            --zone "$id" > "$temp_file" \
        || echo "Failed to generate $resource for $name" >> "$temp_file"

        resp=$(<"$temp_file")

        if [[ $resp == resource* ]]; then
            echo "$resp" > "_${resource}_${name}.tf"
        else
            echo "$resp"
        fi

        rm "$temp_file"
    done
done
```

</details>

<details>
<summary>Zsh only</summary>

```zsh
for resource in "${zone_scoped_resources[@]}"; do
    for name id in ${(kv)zone}; do

        temp_file=$(mktemp)

        echo "$resource $name $id"

        # resp=$(<"$temp_file")

        # if [[ $resp == resource* ]]; then
        #     echo "$resp" > "_${resource}_${name}.tf"
        # else
        #     echo "$resp"
        # fi

        rm "$temp_file"
    done
done
```

</details>

If you're unsure how to start terraform, make a directory (like `./terraform` and create a file called `main.tf` and add the below to it.

once you've created the file, run `terraform init`.

<details>
<summary>Terraform</summary>

```terraform
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

provider "cloudflare" {
}
```

</details>
