### ISSUE TITLE
Unable to run `cf-terraforming` on Mac due to it saying I have tf 1.0.6

### ISSUE THREAD

**Issue by wesleykirkland** [cloudflare/cf-terraforming#484]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

v0.8.4

### Expected outcome

I've ran, with vars pre-populated

```
cf-terraforming generate \                               
  --resource-type "cloudflare_record" \                             
  --zone $CLOUDFLARE_ZONE_ID
```

and I expected it to generate my Terraform code for me.

versions.tf
```hcl
terraform {
  required_version = "~> 1.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.9"
    }

    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
```

provider.tf
```hcl
provider "aws" {
  region = var.region
  default_tags {
    tags = local.common_tags
  }
}

provider "cloudflare" {

}
```

### Actual outcome

FATA[0002] terraform 1.0.6 not supported by configuration (~> 1.1 required)

and 

FATA[0005] terraform 1.0.6 not supported by configuration (~> 1.1 required)

### Steps to reproduce

1. Install cf-terraforming from brew
2. Run cf-terraforming

I'm using tfenv on a M1, though I've had a coworker try it on an Intel MBP.

### References

This is the only reference I've found and I've scanned my entire path and I only have one Terraform binary

https://devscope.io/code/cloudflare/cf-terraforming/issues/467#comment2716178

Path

```
/Users/wesley.kirkland/.pyenv/shims
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/System/Cryptexes/App/usr/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/wesley.kirkland/.local/bin
```

**Comment by jacobbednarz** [comment]
this is saying your configuration is wanting 1.1 however 1.0.6 is in the tool. you can remove the version constraint and have this work. 

in future we'll look at providing a way to define a minimum version instead.

**Comment by wesleykirkland** [comment]
@jacobbednarz Can this hard requirement but documented please? The only reason I found it was from a fellow coworker and you in this issue.
