### ISSUE TITLE
Generate/import wrapper

### ISSUE THREAD

**Issue by vanmash** [cloudflare/cf-terraforming#544]
### Current `cf-terraforming` version

0.11.0

### Description

a wrapper to generate and import ALL types

### Use cases

Allow to import all configuration in one step

### Potential `cf-terraforming` usage

`cf-terraforming generate-all` - generated configs for all resources types

**Comment by jacobbednarz** [comment]
see #194 why this isn’t something we’ve added (and no plans to at the moment).
