### ISSUE TITLE
Generating tunnels fails

### ISSUE THREAD

**Issue by tsrats** [cloudflare/cf-terraforming#547]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.12.0

### Expected outcome

Output tunnels from account.

### Actual outcome

 $ cf-terraforming generate --resource-type cloudflare_tunnel --account $CLOUDFLARE_ACCOUNT_ID -v
...lots of output...
{"success":true,"messages":[],"errors":[],"result":"stringofcharacters"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100aa1804]

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0x101012080?, {0x100aaa8f8?, 0x5?, 0x5?})
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:1102 +0x3f14
github.com/spf13/cobra.(*Command).execute(0x101012080, {0x140001ceb40, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x101011da0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
	/home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x24
main.main()
	/home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x1c
$

### Steps to reproduce

1. Set account ID and API token
2. Run `cf-terraforming generate --resource-type cloudflare_tunnel --account $CLOUDFLARE_ACCOUNT_ID`

**Comment by jonod8698** [comment]
+1 latest version.

$ cf-terraforming generate --account $CLOUDFLARE_ACCOUNT_ID --resource-type "cloudflare_tunnel"

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x5e6348]

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0xb76ce0?, {0x6fa17e?, 0x4?, 0x4?})
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:1102 +0x5248
github.com/spf13/cobra.(*Command).execute(0xb76ce0, {0xc00009f700, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xb76a00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x25
main.main()
        /home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x17

**Comment by ApatheticRiku** [comment]
+1

cf-terraforming generate --resource-type cloudflare_tunnel > tunnel.tf 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x93a4c8]

goroutine 1 [running]:
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.generateResources.func1(0xeb1260?, {0xa4b7f3?, 0x2?, 0x2?})
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/generate.go:1102 +0x5248
github.com/spf13/cobra.(*Command).execute(0xeb1260, {0xc00007ac60, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xeb0f80)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd.Execute()
        /home/runner/work/cf-terraforming/cf-terraforming/internal/app/cf-terraforming/cmd/root.go:30 +0x25
main.main()
        /home/runner/work/cf-terraforming/cf-terraforming/cmd/cf-terraforming/main.go:8 +0x17

**Comment by ApatheticRiku** [comment]
I was receiving this error message as well. Came down to the version of my CloudFlare provider. I was on 3.x. After updating my required_providers to 4.x and re-running `terraform init` the error went away.
@tsrats Can you verify this works for you as well?

**Comment by tsrats** [comment]
Hi @ApatheticRiku! Yes, changing to `version = "~> 4.0"` worked for me as well, thank you!
