### ISSUE TITLE
Missing value for CAA cloudflare_record

### ISSUE THREAD

**Issue by deppy** [cloudflare/cf-terraforming#55]
The cloudflare_record CAA records don't appear correct.  There is no "value" set for CAA records.

When I ran `go run cmd/cf-terraforming/main.go --email $CLOUDFLARE_EMAIL --key $CLOUDFLARE_TOKEN --account $CLOUDFLARE_ACCOUNT_ID all` I get the following resource:

```
resource "cloudflare_record" "CAA_example_com_ee7c46060f3f700960bbc5b1c81d3deb" {
    domain = "example.com"

    name = "example.com"
    type = "CAA"
    ttl = "1"
    proxied = "false"

}
```

**Comment by deppy** [comment]
The Cloudflare API doesn't even support configuration of CAA records, so either cf-terraforming should completely ignore those records, or the API should be expanded to support CAA records. I've opened a support request with Cloudflare to get an answer about expanding the API to support CAA records.

**Comment by rufoa** [comment]
Same problem here. Issue not stale
