### ISSUE TITLE
error generating load_balancer_pool and load_balancer_monitor

### ISSUE THREAD

**Issue by EngZaz** [cloudflare/cf-terraforming#550]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.12.0

### Expected outcome

i expected to see a list of all load balancer pools and monitors

### Actual outcome

FATA[0002] Could not route to /client/v4/accounts/load_balancers/pools, perhaps your object identifier is invalid? (7003)
and
Could not route to /client/v4/accounts/load_balancers/monitors, perhaps your object identifier is invalid? (7003) 

### Steps to reproduce

1- install cf-terraforming as mentioned in Readme file
2- create a new folder and create a provider.tf file 

at the provider.tf file

terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
3- terraform init in the folder has the provider.tf file

4- run the generate command
cf-terraforming generate --resource-type "cloudflare_load_balancer_monitor" --zone 1234 --> add the correct zone id
cf-terraforming generate --resource-type "cloudflare_load_balancer_pool" --zone 1234 --> add the correct zone id

5- if i use the account id
cf-terraforming generate --resource-type "cloudflare_load_balancer_pool" -a 123 --> add your account id i get this error
FATA[0000] --account and --zone are mutually exclusive, support for both is deprecated

**Comment by jacobbednarz** [comment]
both `cloudflare_load_balancer_monitor` and `cloudflare_load_balancer_pool` are account level resources, so providing the zone ID isn't going to generate anything. you only need to provide `account-id` per the error you've posted above.

**Comment by EngZaz** [comment]
i get an error when i use the account
cf-terraforming generate --resource-type "cloudflare_load_balancer_pool" -a 123 --> add your account id i get this error
FATA[0000] --account and --zone are mutually exclusive, support for both is deprecated
even though i didn't mention the zone ID it still gives me the error

**Comment by jacobbednarz** [comment]
if you're not providing it in the command, it must be picking it up from the environment variable (`cf-terraforming` supports reading from both).

**Comment by EngZaz** [comment]
You are right. The reason was I ran this command earlier
export CLOUDFLARE_ZONE_ID=123

once I used a new terminal, the below command showed the output
cf-terraforming generate --resource-type "cloudflare_load_balancer_pool" -a 123 

Thanks!
