### ISSUE TITLE
[BUG] "--account and --zone are mutually exclusive"

### ISSUE THREAD

**Issue by boomam** [cloudflare/cf-terraforming#575]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.12.0

### Expected outcome

Example generation code from [doc site](https://developers.cloudflare.com/terraform/advanced-topics/import-cloudflare-resources/) to work.

### Actual outcome

Error of - 
```
level=fatal msg="--account and --zone are mutually exclusive, support for both is deprecated"
```
tf files referenced in commands do create, but are blank.  

### Steps to reproduce

1. Setup provider as per doc steps
2. Initialize TF
3. Add variables as environment variables
4. Run -
```
cf-terraforming generate --resource-type cloudflare_record --email $CLOUDFLARE_EMAIL --token $CLOUDFLARE_API_TOKEN --zone $CLOUDFLARE_ZONE_ID >> cloudflare.tf
```

This has also been tested on Win11 (test above is MacOS), with the adjusted demo code of - 
```
cf-terraforming generate --resource-type cloudflare_record --zone $CLOUDFLARE_ZONE_ID >> cloudflare.tf
```

**Comment by boomam** [comment]
Interesting - re-creating the API Token (same scope) resolves the issue, but instead gives me a long-winded "invalid request headers'" error.

**Comment by boomam** [comment]
@jacobbednarz i am unsure why this has been closed?
Can you elaborate please?

**Comment by jacobbednarz** [comment]
the example from the doc site does work and the conflicting flags are an indication that you either have the flags set or the values provided via environment variables. you should audit your environment for those values.

**Comment by boomam** [comment]
Yup, thats what I've done, several times over.
The issue persists and i can duplicate this across OS's too.

**Comment by boomam** [comment]
Can you expand on "the second error is stating that your API token format is incorrect." - how would you expect this to be?

The token entered as a variable is the exact token format exported from the CF dashboard. It can be in no other format?

**Comment by jacobbednarz** [comment]
you need to make sure you are using the correct flags for API tokens and API keys (they are different formats). see https://developers.cloudflare.com/fundamentals/api/get-started/keys/ vs https://developers.cloudflare.com/fundamentals/api/get-started/create-token/

if you're having issues with the configuration file, I'd recommend you open an issue specific to that as this reproduces just fine without the file.
