### ISSUE TITLE
Multiple Domains Cannot be Specified in Access Application Creation When Using Terraform

### ISSUE THREAD

**Issue by PZunit** [cloudflare/cf-terraforming#589]
### Current `cf-terraforming` version

version = ">= 4, < 5"

### Description

Dear Cloudflare Team,

Hope you are well.

We would like to report an issue when creating/importing Cloudflare ZeroTrust Access Applications through Terraform. Through The ZeroTrust console, it is possible to add several subdomains in the "Application domain" section of the Access Application creation. But, when importing the same application through Terraform or when you want to create a new one using Terraform, it is not possible to specify multiple domains as the "domain" attribute in the Terraform code only accepts strings and not lists. Even the access policy is imported, only the first subdomain is imported and shown in the Terraform code and the rest of the subdomains are not shown.
I have already raised a support ticket and they have mentioned that I need to raise this issue here as a feature request.
Let me know if anything else is needed.

Many thanks for your kind support.

Regards,
Parsa
![How Terraform Import our Access Application with several Sub-domains](https://github.com/cloudflare/cf-terraforming/assets/108528160/ed1243cd-50f1-4878-b0ce-7a781137ccc8)

### Use cases

Creating Zero Trust Access Application with several domains through Terraform/Importing existing Zero Trust Access Application with several domains in Terraform

### Potential `cf-terraforming` usage

The domain attribute under the cloudflare_access_application resource should accept lists as value so that several domains can be added to it just like it is possible on the console.

**Comment by kennyj42** [comment]
Hi there, please use this field: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application#self_hosted_domains to set multiple domains. The "domain" field will be the primary domain that is used for the App Launcher and table view of applications.

**Comment by PZunit** [comment]
Thank you so much @kennyj42 . Apologise for the very late response. The issue was solved
