### ISSUE TITLE
Specified workspace "name" conflicts with TF_WORKSPACE environment variable

### ISSUE THREAD

**Issue by mudge** [cloudflare/cf-terraforming#619]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

cf-terraforming v0.13.0

### Expected outcome

Running `cf-terraforming generate` against a Terraform directory using Terraform Cloud to store state should produce the expected Terraform configuration from the relevant Cloudflare zone.

### Actual outcome

`cf-terraforming` produces the following fatal error (with the `--verbose` flag):

```
DEBU[0000] initializing cloudflare-go with API Token     account_Id= zone_id=ZONE-ID-HERE
DEBU[0003] initializing Terraform in .                  
DEBU[0003] reading Terraform schema for Cloudflare provider 
FATA[0003] failed to read provider schemaexit status 1

Error: Invalid workspaces configuration

Specified workspace "name" conflicts with TF_WORKSPACE environment variable.

The 'workspaces' block configures how Terraform CLI maps its workspaces for
this single
configuration to workspaces within a Terraform Cloud organization. Two
strategies are available:

tags - A set of tags used to select remote Terraform Cloud
workspaces to be used for this single
configuration. New workspaces will automatically be tagged with these tag
values. Generally, this
is the primary and recommended strategy to use.  This option conflicts with
"name".

name - The name of a single Terraform Cloud workspace to be used
with this configuration.
When configured, only the specified workspace can be used. This option
conflicts with "tags"
and with the TF_WORKSPACE environment variable.
```

### Steps to reproduce

1. Install Terraform 1.6.1
2. Create a new directory with a single `main.tf` containing the following, where the organization name and workspace name are set to a Terraform Cloud workspace with "Execution mode: Local" and the environment contains an appropriate `CLOUDFLARE_API_TOKEN`

```terraform
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }

  cloud {
    organization = "ORGANIZATION-NAME-HERE"

    workspaces {
      name = "WORKSPACE-NAME-HERE"
    }
  }
}

provider "cloudflare" {
}
```
3. Try to generate Terraform resources with `cf-terraforming generate --email $CLOUDFLARE_EMAIL --token $CLOUDFLARE_API_TOKEN -z $CLOUDFLARE_ZONE_ID --resource-type cloudflare_ruleset` (where `CLOUDFLARE_EMAIL`, `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_ZONE_ID` are set appropriately)

### References

This error message is mentioned in the following bugs for Terraform 1.6.0 but I'm seeing this behaviour with 1.5.7 and 1.6.1 too:

* https://github.com/hashicorp/terraform/issues/34046
* https://github.com/hashicorp/terraform/issues/33976

**Comment by mudge** [comment]
I notice there is a 0.14.0 of cf-terraforming available on GitHub but [not Homebrew](https://github.com/cloudflare/homebrew-cloudflare/blob/master/Casks/cf-terraforming.rb)?

**Comment by mudge** [comment]
Upgrading to 0.14.0 fixes this so I have raised https://github.com/cloudflare/homebrew-cloudflare/pull/68

**Comment by jacobbednarz** [comment]
this is not a bug in cf-terraforming but the version of terraform being used. within cf-terraforming, if a local CLI version isn't detected it will download and use the latest. you can also solve this by having an initialised terraform project with an older version of the terraform CLI configured.
