### ISSUE TITLE
Use of internal package not allowed

### ISSUE THREAD

**Issue by instance-id** [cloudflare/cf-terraforming#62]
Hello,  
I keep getting the following error every time I try to run this.

    cmd/cf-terraforming/main.go:3:8: use of internal package github.com/cloudflare/cf-terraforming/internal/app/cf-terraforming/cmd not allowed

I am not quite sure what I am supposed to do about this, do I need to change something?

Thanks,

**Comment by patryk** [comment]
What command do you actually run? What version of Go you have?
