### ISSUE TITLE
Add 'standard' usage_model to Cloudflare Pages

### ISSUE THREAD

**Issue by khalil-omer** [cloudflare/cf-terraforming#636]
### Current `cf-terraforming` version

4.19

### Description

Unbound and bundled are deprecated. 

### Use cases

Cloudflare best practice for Workers

### Potential `cf-terraforming` usage

Deploying Pages sites

**Comment by jacobbednarz** [comment]
this tool only handles exporting the existing resources created in Cloudflare and as such, doesn't have the ability to define these attributes. you're probably looking for the [terraform provider](https://github.com/cloudflare/terraform-provider-cloudflare/).
