### ISSUE TITLE
Turnstile with "no" domains generates invalid config

### ISSUE THREAD

**Issue by punkeel** [cloudflare/cf-terraforming#655]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.16.1

### Expected outcome

cf-terraforming generates valid blocks for all possible configurations.

### Actual outcome

cf-terraforming generates invalid code blocks :(

```console
╷
│ Error: Missing required argument
│ 
│   on turnstile_widgets.tf line 20, in resource "cloudflare_turnstile_widget" "terraform_managed_resource_...":
│   20: resource "cloudflare_turnstile_widget" "terraform_managed_resource_..." {
│ 
│ The argument "domains" is required, but no definition was found.
╵
```

The generated block should include `domain = []`, likely because it is the default "Go" value for an array.

### Steps to reproduce

1. Get the entitlement for not specifying any domains
2. Create a Turnstile widget with an empty list of domains
3. Try to import it

Note: this requires a paid entitlement.

**Comment by jacobbednarz** [comment]
if you didn't need to provide domains, wouldn't you expect _not_ to have them present anywhere? i suspect this is a change that should be made in the [provider](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/framework/service/turnstile/schema.go#L49-L52) instead to make `domains` optional instead (which in turn, will be correctly handled here since the schema will dictate it can be empty and not generate an attribute for it.

**Comment by punkeel** [comment]
> if you didn't need to provide domains
I'd say the opposite: I need to provide the empty list. 

99.9% of users must provide a list of domains as they won't have the entitlement. The 0.1% of users who _can_ not provide it **must** do it on purpose, not by mistake. 

I don't think the provider is wrong here - but happy to be convinced otherwise

Note for clarity & future reference: I'm on the Turnstile team

**Comment by jacobbednarz** [comment]
needing to explicitly provide an empty list feels a little wrong (similar to initialising empty blocks like `foo {}`) but i don't feel strongly about it. 

i'm happy to review a PR that updates the mappings to always provide the value (even an empty list) which can later be populated with additional domains if they are present. there are quite a few examples of prior art in the generation if you're keen to take a pass at this.

**Comment by punkeel** [comment]
I strongly believe the list of domains should _always_ be present in the Terraform configuration, it is a fundamental part of a Turnstile widget, and a `default` value doen't exist for it.
The empty list has a special meaning (not a **default** value!)–if we could represent this using enums, we would likely use `AnyHostname | NonEmptyListOfDomains(string[])`.

During their lifetimes, widgets will more likely switch `NonEmptyListOfDomains -> AnyHostname` than back.


At creation time, `domains` is required by the API (it can be empty iff you have the entitlement).
When updating a widget, we distinguish between the absence of the `domains` field (don't update it), and the empty list (update the list to be empty).

(Now that I think of it, I'm not sure [cloudflare-go](https://github.com/cloudflare/cloudflare-go/blob/cd4e10f45c055a6f12361a1972a755ed5082bcb1/turnstile.go#L40) allows this... oops)


I don't know how Terraform would behave if you didn't specify a list of domains - would it try to empty the list of domains, or leave it unchanged. Making it a required guarantees tf will do the right thing: what the code block says! (this concern may very well be made up!)


---


I opened #659 for this. I tried to keep it short & simple

**Comment by Debagnik** [comment]
Do anyone have any clue why was my simple project was mentioned on this thread?

**Comment by punkeel** [comment]
the opposite, the PR on your project is mentioning cf-terraforming

seems to be https://github.com/Debagnik/project-walnut/pull/68#pullrequestreview-2762373827

**Comment by Debagnik** [comment]
@punkeel 

Kinda strange. Anyways Seems like the Review comment left by that AI had accidentally left a # 655 somewhere. I didn't find it.

Thanks for the clarity tho.
