### ISSUE TITLE
there is no package cached in .terraform\providers

### ISSUE THREAD

**Issue by biker2o** [cloudflare/cf-terraforming#662]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

-dev+11f3e2f0d4f6

### Expected outcome

Run the generate command to generate all ruleset configurations for a zone, as described in the Firewall Rules -> Custom Rules [migration guide](https://developers.cloudflare.com/waf/reference/migration-guides/firewall-rules-to-custom-rules/#replace-your-configuration-using-cf-terraforming): 

### Actual outcome

cf-terraforming cannot find  cloudflare/cloudflare, hashicorp/aws, and hashicorp/random cached packages in .terraform\providers

```
C:\REDACTED>cf-terraforming generate --zone REDACTED --resource-type "cloudflare_ruleset" -t $CLOUDFLARE_API_TOKEN
time="2024-01-05T15:00:30-06:00" level=fatal msg="failed to read provider schemaexit status 1\n\nError: Required plugins are not installed\n\nThe installed provider plugins are not consistent with the packages selected\nin the dependency lock file:\n  - registry.terraform.io/cloudflare/cloudflare: there is no package for registry.terraform.io/cloudflare/cloudflare 4.21.0 cached in .terraform\\providers\n  - registry.terraform.io/hashicorp/aws: there is no package for registry.terraform.io/hashicorp/aws 5.31.0 cached in .terraform\\providers\n  - registry.terraform.io/hashicorp/random: there is no package for registry.terraform.io/hashicorp/random 3.6.0 cached in .terraform\\providers\n\nTerraform uses external plugins to integrate with a variety of different\ninfrastructure services. You must install the required plugins before running\nTerraform operations.\n\n"
```

### Steps to reproduce

terraform init | SUCCESSFUL
terraform plan | SUCCESSFUL
cf-terraforming generate --zone REDACTED --resource-type "cloudflare_ruleset" -t $CLOUDFLARE_API_TOKEN | ERROR

[ExampleErrorAndVersions.txt](https://github.com/cloudflare/cf-terraforming/files/13846698/ExampleErrorAndVersions.txt)

[TerraformLockFile.txt](https://github.com/cloudflare/cf-terraforming/files/13846699/TerraformLockFile.txt)

<img width="157" alt="TerraformFolderDirectories" src="https://github.com/cloudflare/cf-terraforming/assets/69684276/9cf39730-91d0-4d6c-adac-112ecd609180">

**Comment by jacobbednarz** [comment]
this doesn't seem to be a problem with cf-terraforming but your local installation. this is working for me on windows and on Mac. 

perhaps try a clean setup and initialisation?

**Comment by syonfoppen** [comment]
Same issue here, using the `--terraform-binary-path` option pointed to my terraform binary worked for me :)

**Comment by biker2o** [comment]
@syonfoppen That worked! Thank you!!

cc: @jacobbednarz
