### ISSUE TITLE
Authentication Error (10000)

### ISSUE THREAD

**Issue by robcohen** [cloudflare/cf-terraforming#677]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.18.0

### Expected outcome

When I run `cf-terraforming generate --zone $CLOUDFLARE_ZONE --resource-type "cloudflare_record"`
I should get a valid .tf output from the DNS config on cloudflare.

### Actual outcome

Instead I get "Authentication Error"

### Steps to reproduce

Created cloudlfare API token with:
Zone -> Zone -> Edit
Zone -> DNS -> Read

Include -> All Zones from an account -> <NAMEOFACCOUNT>

run `cf-terraforming generate --zone $CLOUDFLARE_ZONE --resource-type "cloudflare_record"`

Get authentication error.

When I replace the CLOUDFLARE_API_KEY with the Cloudflare Global API Key, everything works.
Thus, it is a permission issue with the key. 
However, the documentation for cf-terraforming DOES NOT give any advice for how permissions should be configured for the key. 

A few suggested changes:
- Change the docs to explain what permissions will allow for use of the CLI tool
- Change error message so improper permissions are explained so proper configuration of the key can be made.
- Link to docs where proper permissioning is explained.

**Comment by jacobbednarz** [comment]
we don't have per tool permissioning notes since all of the tools are just another HTTP client to our API. instead, you need to use a combination of the developer docs for the endpoints you are trying to call and a little bit of trial and error. the latter isn't ideal however there are some improvements penciled in for down the track.

**Comment by starcraft66** [comment]
I solved this issue by using the zone id instead of my account id on the command line.
