### ISSUE TITLE
Output CF resources in a way that terraform can iterate over using for_each

### ISSUE THREAD

**Issue by scott-doyland-burrows** [cloudflare/cf-terraforming#683]
### Current `cf-terraforming` version

latest

### Description

We have ~20 zones, and ~1000 records to import.

The current cf-terraforming will generate ~1000 individual terraform resources.

This isn't how anyone would write terraform code from scratch.

I would like to see an option in cf-terraforming to output the cloudflare resources in a format that terraform can iterate over by using ```for``` to further format the data into a format suitable for ```for_each```.

Below is how I would like the records to be output.  I would like the CF resource ID to still be output as per the example ```imported_resource_id```.

```
cloudflare_records = [
  {
    imported_resource_id = "123"
    name                 = "tw"
    proxied              = false
    ttl                  = 1
    type                 = "NS"
    value                = "plato.ns.cloudflare.com"
    zone_id              = "qwerty"
  },
  {
    imported_resource_id = "456"
    name                 = "tw"
    proxied              = false
    ttl                  = 1
    type                 = "NS"
    value                = "diana.ns.cloudflare.com"
    zone_id              = "qwerty"
  },
  {
    imported_resource_id = "789"
    name                 = "_sipfederationtls._tcp.service"
    priority             = 100
    proxied              = false
    ttl                  = 3600
    type                 = "SRV"
    zone_id              = "qwerty"
    data = {
      name     = "service.example.com"
      port     = 5061
      priority = 100
      proto    = "_tcp"
      service  = "_sipfederationtls"
      target   = "sipfed.online.lync.com"
      weight   = 1
    }
  }
]
```

Once in this format, we only need one terraform ```cloudflare_record``` resource and can iterate over the above.

I think this is a much more sensible approach than having multiple terraform resources.

Ideally, there would be a cf-terraforming option to be able to obtain the data in this format.

### Use cases

As mentioned above, my use case is not wanting to have over 1000 terraform resources in a ```.tf``` file.

Instead I use terraform's ```for_each``` feature to have one terraform resource.

Using a variable of type ```object``` also allows me to set defaults for the values.

An example of my code would be as follows - which will iterate over the data shown above.

It would not really matter too much on the output format, as long as ```for``` can iterate over it to produce a format I want to work with.

```
variable "cloudflare_record" {
  type = list(object({
    imported_resource_id = optional(string, null)
    name                 = string
    ttl                  = optional(number, 1)
    type                 = string
    value                = optional(string, null)
    priority             = optional(number, null)
    proxied              = optional(bool, false)
    comment              = optional(string, "")
    data = optional(object({
      algorithm      = optional(number, 0)
      altitude       = optional(number, 0)
      digest_type    = optional(number, 0)
      key_tag        = optional(number, 0)
      lat_degrees    = optional(number, 0)
      lat_minutes    = optional(number, 0)
      lat_seconds    = optional(number, 0)
      long_degrees   = optional(number, 0)
      long_minutes   = optional(number, 0)
      long_seconds   = optional(number, 0)
      matching_type  = optional(number, 0)
      name           = optional(string, null)
      order          = optional(number, 0)
      port           = optional(number, null)
      precision_horz = optional(number, 0)
      precision_vert = optional(number, 0)
      preference     = optional(number, 0)
      priority       = optional(number, 100)
      proto          = optional(string, null)
      protocol       = optional(number, 0)
      selector       = optional(number, 0)
      service        = optional(string, null)
      size           = optional(number, 0)
      target         = optional(string, null)
      type           = optional(number, 0)
      usage          = optional(number, 0)
      weight         = optional(number, 1)
    }), null)
  }))

  default = []

  description = "Cloudflare zone records"
}
```

```
locals {
  records = {
    for index, record in var.cloudflare_record :
    record.type != "SRV" ? try(record.key, format("%s-%s-%s", record.name, record.type, record.value)) : try(record.key, format("%s-%s", record.name, record.type)) => record
  }
}
```

```
resource "cloudflare_record" "this" {
  for_each = local.records

  zone_id  = data.cloudflare_zone.zone.id
  name     = each.value.name
  type     = each.value.type
  value    = each.value.value
  priority = each.value.priority
  proxied  = each.value.proxied
  ttl      = each.value.ttl
  comment  = format("%s | %s", var.GITHUB_REPOSITORY, each.value.comment)


  dynamic "data" {
    for_each = each.value.data != null ? [1] : []

    content {
      algorithm      = each.value.data.algorithm
      altitude       = each.value.data.altitude
      digest_type    = each.value.data.digest_type
      key_tag        = each.value.data.key_tag
      lat_degrees    = each.value.data.lat_degrees
      lat_minutes    = each.value.data.lat_minutes
      lat_seconds    = each.value.data.lat_seconds
      long_degrees   = each.value.data.long_degrees
      long_minutes   = each.value.data.long_minutes
      long_seconds   = each.value.data.long_seconds
      matching_type  = each.value.data.matching_type
      name           = each.value.data.name
      order          = each.value.data.order
      port           = each.value.data.port
      precision_horz = each.value.data.precision_horz
      precision_vert = each.value.data.precision_vert
      preference     = each.value.data.preference
      priority       = each.value.data.priority
      proto          = each.value.data.proto
      protocol       = each.value.data.protocol
      selector       = each.value.data.selector
      service        = each.value.data.service
      size           = each.value.data.size
      target         = each.value.data.target
      type           = each.value.data.type
      usage          = each.value.data.usage
      weight         = each.value.data.weight
    }
  }
}
```

### Potential `cf-terraforming` usage

```cf-terraforming generate --zone $CLOUDFLARE_ZONE_ID --resource-type "cloudflare_record" --output data-only```

This would make cf-terraforming output just the CF data, and and not make it hook into terraform at all.

Essentially this is just going to be doing an API call and formatting the data.

**Comment by jacobbednarz** [comment]
thanks for the suggestion however, this isn't something we'll be adding to cf-terraforming. 

there are a few reasons why however, to keep this brief, I'll cover the top two. 

firstly, this tool is far more capable than just as a formatter. it takes the schema, applies parsing rules and then marries the two together taking into account some addition logic we supply for edge cases where the service and API representation may diverge. if you're just after outputting the data in different formats based on the API output, you're better off calling the API yourself and outputting however you need the data. 

secondly, we don't encourage over abstractions like your for/for_each example (or any dynamic expressions really). these lead to hard to debug problems between the provider and user land code and without someone knowing the specifics of the setup at hand, you'll waste hours chasing the logic bug (ask me how I know 🙂). where dynamics are used, they should be intentional and fit for purpose which a tool like cf-terraforming cannot determine accurately alone. 

hope this makes sense and appreciate the time you've put into raising the issue!
