### ISSUE TITLE
Getting error "<resource> is not yet supported for automatic generating" on many from the supported list

### ISSUE THREAD

**Issue by allwalte** [cloudflare/cf-terraforming#684]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.18.0

### Expected outcome

Since cloudflare_teams_location (and a lot of others I tried, but I'll use this as the example) has a green checkmark on the readme list for generation, I expected the resource config to be generated.

### Actual outcome

Received the error `"cloudflare_teams_location" is not yet supported for automatic generation% `.  A small handful of resources (cloudflare_tunnel is one) actually work, so my connection/setup should be fine, but most don't.

### Steps to reproduce

`cf-terraforming generate -v -a <redacted> --resource-type cloudflare_teams_location`

**Comment by jacobbednarz** [comment]
`cloudflare_teams_location` is not yet in a released version. if you would like to use it, you'll need to build from `master` or wait for the next release to include it.
