### ISSUE TITLE
consider reimplementing the use of CI variable or at least documenting its behaviour

### ISSUE THREAD

**Issue by BogdanSorlea** [cloudflare/cf-terraforming#703]
### Current `cf-terraforming` version

latest

### Description

it has been elaborated on a related ticket: https://github.com/cloudflare/cf-terraforming/issues/699#issuecomment-2107478629

### Use cases

when running in CI (e.g. Github Actions) cf-terraformer fails and the reason is not obvious at all

### Potential `cf-terraforming` usage

there is no reason not to use cf-terraforming in CI - e.g. for continuous resource dumps, if one finds that fit

### References

https://github.com/cloudflare/cf-terraforming/issues/699
https://gophers.slack.com/archives/C029RQSEE/p1715344310636629

**Comment by jacobbednarz** [comment]
sorry but this tool isn't intended to be used in CI; it is expected to be run from your local machine and commit the files into your IaC workflow or help you get setup with IaC from an existing clickops style of management. examples are scenarios where you previously didn't manage the config in code, you inherit a zone/account or you're duplicating particular setups.

**Comment by BogdanSorlea** [comment]
not just disappointing, but ridiculous really. you should definitely reconsider.
@jacobbednarz
