### ISSUE TITLE
Generating CF record generates resources with wrong syntax

### ISSUE THREAD

**Issue by seburu** [cloudflare/cf-terraforming#743]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cf-terraforming version

0.20.0

### Expected outcome

resource "cloudflare_record" "terraform_managed_resource_d2665bd6e8ae10091d77d5c502259208" {
  content = "100::"
  name    = "api"
  proxied = true
  ttl     = 1
  type    = "AAAA"
  zone_id = "f786450beacda7599e7e29b5a644bc7e"
}

### Actual outcome

resource "cloudflare_record" "terraform_managed_resource_d2665bd6e8ae10091d77d5c502259208" {
  content = "100::"
  name    = "api"
  proxied = true
  ttl     = 1
  type    = "AAAA"
  value   = "100::"
  zone_id = "f786450beacda7599e7e29b5a644bc7e"
}

### Steps to reproduce

cf-terraforming generate on Cloudflare_record type

**Comment by jacobbednarz** [comment]
this is already fixed on `master`; we're just pending a release so if you'd like to use it, please pull that branch locally and run it in the meantime.
