### ISSUE TITLE
Problem import resources FATA[0001] failed to read provider schemae

### ISSUE THREAD

**Issue by rcor** [cloudflare/cf-terraforming#763]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.9.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.47.0
+ provider registry.terraform.io/hashicorp/aws v5.75.1

### Affected resource(s)

cloudflare_ruleset 
cloudflare_record 
cloudflare_page_rule

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "= 4.47.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.75.1"
    }
  }
}
```

### Link to debug output

https://gist.github.com/rcor/1952885f6db86a15b7b208d3cc5f40e9

### Panic output

FATA[0001] failed to read provider schemaexit status 1

Error: HCP Terraform or Terraform Enterprise initialization required: please run "terraform init"

Reason: HCP Terraform configuration block has changed.

Changes to the HCP Terraform configuration block require reinitialization, to
discover any changes to the available workspaces.

To re-initialize, run:
  terraform init

Terraform has not yet made changes to your existing configuration or state.

### Expected output

I expected a file containing the records in the above mentioned zone.

I have a .sh script I dot slash to export the variables required. This has worked for me previously with no problems at all.

### Actual output

```FATA[0001] failed to read provider schemaexit status 1

Error: HCP Terraform or Terraform Enterprise initialization required: please run "terraform init"

Reason: HCP Terraform configuration block has changed.

Changes to the HCP Terraform configuration block require reinitialization, to
discover any changes to the available workspaces.

To re-initialize, run:
  terraform init

Terraform has not yet made changes to your existing configuration or state.
`

### Steps to reproduce

1- Create a bash file with this content and repalce with the zone id and cloudlflare token 

```
export CLOUDFLARE_API_TOKEN='XXXXXXXXXX'
export CLOUDFLARE_ZONE_ID='XXXXXXXXXX'
resources=("ruleset" "record" "page_rule")
for str in ${resources[@]}; do
  echo $str
  echo "Import $str"
  cf-terraforming import \
  --zone $CLOUDFLARE_ZONE_ID \
  --resource-type "cloudflare_$str" > migrate_$str.sh
  echo "End to import"
  echo "TF"
  
  cf-terraforming generate \
  --zone $CLOUDFLARE_ZONE_ID \
  --resource-type "cloudflare_$str" > $str.tf
  sed -i 's/"${CLOUDFLARE_ZONE_ID}"/cloudflare_zone.this.id/g'  $str.tf
  echo "End of TF"
done
```

### Additional factoids

I already run terraform init, i upgrade to the lastest version 

### References

_No response_

**Comment by jacobbednarz** [comment]
`FATA[0001] failed to read provider schema` is an indication that the tool is unable to find the provider schema. you'll need to follow the instructions and re-initialise or install the provider for cf-terraforming to be able to read it.

the latest version of both the provider and `cf-terraforming` are working as expected for me.
