### ISSUE TITLE
WAF rules aren't fully exported

### ISSUE THREAD

**Issue by jimbobjim123** [cloudflare/cf-terraforming#96]
Due to Pagination, when WAF rules are exported, currently only 20 items from each of the 2 packages get saved - this isn't useful.

Total rule counts
OWASP package currently: "total_count": 2499
Cloudflare package currently: "total_count": 366

I understand it may not be desirable to export all of the WAF rules as it's often the case that many will be left as default but at minimum, a means of exporting rules that have been changed from default would be very useful for Cloudflare (Enterprise) customers wanting to use TF to bootstrap many new zones.

**Comment by techieforfun** [comment]
same issue here for exporting `cloudflare_ruleset` but returns only a limited number of it. Any news after more than 4 years?
